/* Jeu de données de démonstration — 75 châteaux réels, coordonnées approchées.
   Structure identique à celle visée pour l'import Wikidata / POP-Mérimée.
   15 fiches ajoutées le 2026-08-26 (chinon → beaucaire), 25 de plus le même
   jour (nantes → rambouillet), sourcées à la main depuis Wikipédia fr /
   Wikidata ; voir CONTEXT.md §8 pour la suite. */
window.CASTELLUM_FILTERS = {
  epoque: [
    { id: "e1", label: "Xe – XIIe s.", min: 10, max: 12 },
    { id: "e2", label: "XIIIe – XVe s.", min: 13, max: 15 },
    { id: "e3", label: "XVIe – XVIIe s.", min: 16, max: 17 },
    { id: "e4", label: "XVIIIe s. et +", min: 18, max: 21 }
  ],
  type: ["château", "château-fort", "forteresse", "manoir", "maison forte", "motte castrale", "palais", "domaine", "ruines", "enceinte fortifiée"],
  etat: ["Intact / restauré", "Bon état", "Partiellement ruiné", "Ruines", "Vestiges"],
  acces: ["Ouvert au public", "Visite partielle", "Privé, non visitable", "Extérieurs uniquement"]
};

/* Titres Wikipédia fr — servent à récupérer la photo de chaque fiche
   (vignette basse résolution mise en cache, version haute résolution en ligne). */
window.CASTELLUM_WIKI = {
  chambord: "Château de Chambord",
  chenonceau: "Château de Chenonceau",
  versailles: "Château de Versailles",
  carcassonne: "Cité de Carcassonne",
  gaillard: "Château-Gaillard (Les Andelys)",
  pierrefonds: "Château de Pierrefonds",
  vincennes: "Château de Vincennes",
  fougeres: "Château de Fougères",
  angers: "Château d'Angers",
  amboise: "Château d'Amboise",
  azay: "Château d'Azay-le-Rideau",
  usse: "Château d'Ussé",
  vitre: "Château de Vitré",
  beynac: "Château de Beynac",
  castelnaud: "Château de Castelnaud",
  bonaguil: "Château de Bonaguil",
  koenigsbourg: "Château du Haut-Kœnigsbourg",
  chantilly: "Château de Chantilly",
  fontainebleau: "Château de Fontainebleau",
  cheverny: "Château de Cheverny",
  villandry: "Château de Villandry",
  suscinio: "Château de Suscinio",
  peyrepertuse: "Château de Peyrepertuse",
  montsegur: "Château de Montségur",
  coucy: "Château de Coucy",
  loches: "Château de Loches",
  tarascon: "Château de Tarascon",
  salses: "Forteresse de Salses",
  murol: "Château de Murol",
  ango: "Manoir d'Ango",
  boves: "Château de Boves",
  tournoel: "Château de Tournoël",
  blois: "Château de Blois",
  foix: "Château de Foix",
  reignac: "Maison forte de Reignac",
  chinon: "Forteresse royale de Chinon",
  saumur: "Château de Saumur",
  sully: "Château de Sully-sur-Loire",
  vauxlevicomte: "Château de Vaux-le-Vicomte",
  sedan: "Château de Sedan",
  falaise: "Château de Falaise",
  josselin: "Château de Josselin",
  kerjean: "Château de Kerjean",
  lalatte: "Fort la Latte",
  roquetaillade: "Château de Roquetaillade",
  if: "Château d'If",
  avignon: "Palais des papes d'Avignon",
  val: "Château de Val",
  bussyrabutin: "Château de Bussy-Rabutin",
  beaucaire: "Château de Beaucaire",
  nantes: "Château des ducs de Bretagne",
  brissac: "Château de Brissac",
  tiffauges: "Château de Tiffauges",
  pau: "Château de Pau",
  larochefoucauld: "Château de La Rochefoucauld",
  oiron: "Château d'Oiron",
  nerac: "Château de Nérac",
  grignan: "Château de Grignan",
  annecy: "Château d'Annecy",
  chambery: "Château des ducs de Savoie",
  sisteron: "Citadelle de Sisteron",
  baux: "Château des Baux-de-Provence",
  bonifacio: "Citadelle de Bonifacio",
  luneville: "Château de Lunéville",
  hautbarr: "Château du Haut-Barr",
  bazoches: "Château de Bazoches",
  cormatin: "Château de Cormatin",
  ancyfranc: "Château d'Ancy-le-Franc",
  besancon: "Citadelle de Besançon",
  rambures: "Château de Rambures",
  hardelot: "Château d'Hardelot",
  fere: "Château de Fère-en-Tardenois",
  carrouges: "Château de Carrouges",
  caen: "Château de Caen",
  rambouillet: "Château de Rambouillet"
};

/* Deux fichiers Commons n'exposent aucun auteur dans leurs métadonnées, alors
   que leur licence CC BY-SA impose de citer. Auteurs relevés à la main sur la
   page du fichier le 2026-08-26 ; ce repli ne s'applique que si l'API ne
   renvoie rien, pour ne pas masquer une métadonnée corrigée depuis. */
window.CASTELLUM_PHOTO_CREDITS = {
  /* Auteur déclaré dans le wikitexte de la page, absent du champ Artist. */
  chenonceau: { auteur: "Raph" },
  /* Aucun auteur déclaré : seul le téléverseur est connu. */
  fougeres: { auteur: "Gratyn (téléverseur — aucun auteur déclaré)" }
};

window.CASTELLUM = [
  {
    id: "chambord", n: "Château de Chambord", v: ["Chambourg", "Domaine national de Chambord"],
    t: "château", sc: [16], per: "1519 – 1547", arch: "Attribué à Domenico da Cortona, chantier de François Ier",
    prop: ["François Ier", "Maison d'Orléans", "Maurice de Saxe", "État français (depuis 1930)"],
    ev: ["Chantier lancé par François Ier en 1519", "Séjours de Louis XIV et représentations de Molière", "Dépôt d'œuvres du Louvre en 1939-1945"],
    desc: "Plan centré à donjon cantonné de quatre tours, 440 pièces, escalier à double révolution et terrasses habitées peuplées de lanternes et cheminées.",
    st: ["Renaissance française"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Chambord", dep: "Loir-et-Cher (41)", reg: "Blésois / Orléanais", lat: 47.6160, lng: 1.5170,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.chambord.org" }]
  },
  {
    id: "chenonceau", n: "Château de Chenonceau", v: ["Château des Dames"],
    t: "château", sc: [16], per: "1513 – 1521, galerie 1576",
    arch: "Thomas Bohier, Philibert Delorme (galerie sur le Cher)",
    prop: ["Famille Bohier", "Diane de Poitiers", "Catherine de Médicis", "Famille Menier"],
    ev: ["Donné par Henri II à Diane de Poitiers", "Hôpital militaire en 1914-1918", "Ligne de démarcation en 1940-1942"],
    desc: "Corps de logis carré posé sur les piles d'un ancien moulin, prolongé par une galerie à deux étages franchissant le Cher.",
    st: ["Renaissance française", "Gothique tardif"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Chenonceaux", dep: "Indre-et-Loire (37)", reg: "Touraine", lat: 47.3247, lng: 1.0704,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.chenonceau.com" }]
  },
  {
    id: "versailles", n: "Château de Versailles", v: ["Palais de Versailles"],
    t: "palais", sc: [17, 18], per: "1623 – 1789",
    arch: "Louis Le Vau, Jules Hardouin-Mansart, André Le Nôtre (jardins)",
    prop: ["Louis XIII", "Louis XIV", "État français"],
    ev: ["Installation de la cour en 1682", "Signature du traité de Versailles en 1919", "Journées d'octobre 1789"],
    desc: "Enveloppe du pavillon de chasse de Louis XIII par une façade de marbre, galerie des Glaces de 73 m, aile du Midi et parc dessiné à la française.",
    st: ["Classicisme français", "Baroque"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Versailles", dep: "Yvelines (78)", reg: "Île-de-France", lat: 48.8049, lng: 2.1204,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.chateauversailles.fr" }]
  },
  {
    id: "carcassonne", n: "Cité de Carcassonne", v: ["Château comtal", "Carcaso"],
    t: "enceinte fortifiée", sc: [12, 13, 19], per: "XIIe s., remparts XIIIe s., restauration 1853-1879",
    arch: "Eugène Viollet-le-Duc (restauration)",
    prop: ["Vicomtes Trencavel", "Couronne de France", "État français"],
    ev: ["Siège de 1209 pendant la croisade albigeoise", "Déclassement militaire en 1804", "Restauration par Viollet-le-Duc"],
    desc: "Double enceinte de 3 km, 52 tours, château comtal adossé au rempart occidental et lices entre les deux murs.",
    st: ["Roman", "Gothique", "Restauration du XIXe s."], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Carcassonne", dep: "Aude (11)", reg: "Languedoc", lat: 43.2061, lng: 2.3639,
    plan: true, liens: [{ label: "Centre des monuments nationaux", url: "https://www.remparts-carcassonne.fr" }]
  },
  {
    id: "gaillard", n: "Château-Gaillard", v: ["Castrum de Roche d'Andely"],
    t: "ruines", sc: [12], per: "1196 – 1198", arch: "Commandé par Richard Cœur de Lion",
    prop: ["Duché de Normandie", "Couronne de France", "Commune des Andelys"],
    ev: ["Siège de Philippe Auguste en 1203-1204", "Démantèlement ordonné en 1599"],
    desc: "Éperon barré au-dessus de la Seine : donjon cylindrique à becs, chemise ondulée et triple enceinte étagée.",
    st: ["Architecture militaire anglo-normande"], etat: "Ruines",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Visite partielle",
    com: "Les Andelys", dep: "Eure (27)", reg: "Normandie", lat: 49.2381, lng: 1.4083,
    plan: true, liens: []
  },
  {
    id: "pierrefonds", n: "Château de Pierrefonds", v: ["Pierrefonds-le-Château"],
    t: "château-fort", sc: [14, 19], per: "1393 – 1407, reconstruction 1857-1885",
    arch: "Jean Le Noir, puis Eugène Viollet-le-Duc",
    prop: ["Louis d'Orléans", "Napoléon Ier", "État français"],
    ev: ["Démantèlement sous Richelieu en 1617", "Reconstruction pour Napoléon III"],
    desc: "Quadrilatère à huit tours d'angle, chemin de ronde couvert et salle des Preuses ; relecture savante du château fort par le XIXe siècle.",
    st: ["Gothique flamboyant", "Restauration du XIXe s."], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Pierrefonds", dep: "Oise (60)", reg: "Valois / Picardie", lat: 49.3479, lng: 2.9781,
    plan: true, liens: [{ label: "Centre des monuments nationaux", url: "https://www.chateau-pierrefonds.fr" }]
  },
  {
    id: "vincennes", n: "Château de Vincennes", v: ["Donjon de Vincennes"],
    t: "forteresse", sc: [14], per: "1337 – 1410", arch: "Chantier de Philippe VI à Charles V",
    prop: ["Couronne de France", "Armée française", "État français"],
    ev: ["Mort d'Henri V d'Angleterre en 1422", "Prison d'État aux XVIIe-XVIIIe s.", "Exécution de Mata Hari en 1917"],
    desc: "Donjon de 52 m dans sa chemise, enceinte rectangulaire de neuf tours et Sainte-Chapelle royale au flanc est.",
    st: ["Gothique rayonnant"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Vincennes", dep: "Val-de-Marne (94)", reg: "Île-de-France", lat: 48.8425, lng: 2.4358,
    plan: true, liens: [{ label: "Centre des monuments nationaux", url: "https://www.chateau-vincennes.fr" }]
  },
  {
    id: "fougeres", n: "Château de Fougères", v: ["Fulgerium"],
    t: "château-fort", sc: [12, 13, 15], per: "XIIe – XVe s.", arch: "Famille de Fougères, ducs de Bretagne",
    prop: ["Seigneurs de Fougères", "Duché de Bretagne", "Commune de Fougères"],
    ev: ["Prise par Henri II Plantagenêt en 1166", "Coup de main breton de 1449, déclencheur de la reprise de la guerre de Cent Ans"],
    desc: "Deux hectares dans un méandre du Nançon : treize tours, enceinte basse en éperon et tours à canon de la fin du Moyen Âge.",
    st: ["Militaire médiéval breton"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Fougères", dep: "Ille-et-Vilaine (35)", reg: "Bretagne", lat: 48.3527, lng: -1.2075,
    plan: true, liens: []
  },
  {
    id: "angers", n: "Château d'Angers", v: ["Château des ducs d'Anjou"],
    t: "forteresse", sc: [13], per: "1230 – 1240", arch: "Chantier de Blanche de Castille",
    prop: ["Comtes d'Anjou", "Maison Valois-Anjou", "État français"],
    ev: ["Commande de la tenture de l'Apocalypse en 1375", "Rasement partiel ordonné en 1585"],
    desc: "Enceinte de schiste et calcaire à dix-sept tours en damier, sur un promontoire dominant la Maine ; abrite la tenture de l'Apocalypse.",
    st: ["Gothique", "Militaire capétien"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Angers", dep: "Maine-et-Loire (49)", reg: "Anjou", lat: 47.4700, lng: -0.5600,
    plan: true, liens: [{ label: "Centre des monuments nationaux", url: "https://www.chateau-angers.fr" }]
  },
  {
    id: "amboise", n: "Château royal d'Amboise", v: ["Ambacia"],
    t: "château", sc: [15, 16], per: "1492 – 1498", arch: "Chantiers de Charles VIII et Louis XII",
    prop: ["Famille d'Amboise", "Couronne de France", "Fondation Saint-Louis"],
    ev: ["Conjuration d'Amboise en 1560", "Sépulture de Léonard de Vinci dans la chapelle Saint-Hubert"],
    desc: "Terrasse dominant la Loire, logis du Roi à lucarnes gothiques, tours cavalières à rampe et chapelle Saint-Hubert.",
    st: ["Gothique flamboyant", "Première Renaissance"], etat: "Bon état",
    stat: ["Monument historique classé", "Château privé", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Amboise", dep: "Indre-et-Loire (37)", reg: "Touraine", lat: 47.4133, lng: 0.9861,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.chateau-amboise.com" }]
  },
  {
    id: "azay", n: "Château d'Azay-le-Rideau", v: ["Azay-le-Brûlé"],
    t: "château", sc: [16], per: "1518 – 1527", arch: "Gilles Berthelot, maîtrise d'ouvrage de Philippe Lesbahy",
    prop: ["Gilles Berthelot", "Marquis de Biencourt", "État français"],
    ev: ["Incendie du bourg par Charles VII en 1418", "Acquisition par l'État en 1905"],
    desc: "Plan en L posé sur l'Indre, escalier droit à loggias superposées et miroir d'eau sur trois côtés.",
    st: ["Renaissance française"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Azay-le-Rideau", dep: "Indre-et-Loire (37)", reg: "Touraine", lat: 47.2589, lng: 0.4661,
    plan: true, liens: []
  },
  {
    id: "usse", n: "Château d'Ussé", v: ["Château de la Belle au bois dormant"],
    t: "château", sc: [15, 16, 17], per: "XVe – XVIIe s.", arch: "Familles de Bueil et d'Espinay",
    prop: ["Famille de Bueil", "Famille d'Espinay", "Famille de Blacas"],
    ev: ["Séjour de Vauban, gendre du propriétaire", "Inspiration prêtée au conte de Perrault"],
    desc: "Terrasses étagées au-dessus de l'Indre, courtines à mâchicoulis décoratifs et forêt de toitures d'ardoise.",
    st: ["Gothique tardif", "Renaissance", "Classique"], etat: "Bon état",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Rigny-Ussé", dep: "Indre-et-Loire (37)", reg: "Touraine", lat: 47.2494, lng: 0.2919,
    plan: false, liens: []
  },
  {
    id: "vitre", n: "Château de Vitré", v: ["Vitreium"],
    t: "château-fort", sc: [13, 15], per: "XIIIe – XVe s.", arch: "Barons de Vitré, famille de Laval",
    prop: ["Barons de Vitré", "Famille de La Trémoille", "Commune de Vitré"],
    ev: ["Résistance aux sièges anglais de la guerre de Cent Ans", "Réunion des États de Bretagne en 1655"],
    desc: "Plan triangulaire sur éperon, châtelet à deux tours et pont-levis, tour Saint-Laurent et courtines à archères.",
    st: ["Gothique militaire breton"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Vitré", dep: "Ille-et-Vilaine (35)", reg: "Bretagne", lat: 48.1236, lng: -1.2153,
    plan: false, liens: []
  },
  {
    id: "beynac", n: "Château de Beynac", v: ["Beynac-et-Cazenac"],
    t: "château-fort", sc: [12, 13, 14], per: "XIIe – XIVe s.", arch: "Baronnie de Beynac",
    prop: ["Barons de Beynac", "Famille de Beaumont", "Propriétaire privé"],
    ev: ["Occupation par Richard Cœur de Lion vers 1195", "Face à Castelnaud pendant la guerre de Cent Ans"],
    desc: "Falaise de 150 m au-dessus de la Dordogne : donjon roman, double enceinte et salle des États voûtée en berceau brisé.",
    st: ["Roman", "Gothique"], etat: "Bon état",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Beynac-et-Cazenac", dep: "Dordogne (24)", reg: "Périgord", lat: 44.8394, lng: 1.1447,
    plan: false, liens: []
  },
  {
    id: "castelnaud", n: "Château de Castelnaud-la-Chapelle", v: ["Castelnaud-Fayrac"],
    t: "château-fort", sc: [13, 15], per: "XIIIe – XVe s.", arch: "Familles de Castelnaud et de Caumont",
    prop: ["Bernard de Casnac", "Famille de Caumont", "Propriétaire privé"],
    ev: ["Pris par Simon de Montfort en 1214", "Occupations alternées anglaises et françaises au XIVe s."],
    desc: "Donjon barlong, barbacane et tour d'artillerie ; musée de la guerre au Moyen Âge et machines de siège sur la terrasse.",
    st: ["Militaire médiéval"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Castelnaud-la-Chapelle", dep: "Dordogne (24)", reg: "Périgord", lat: 44.8175, lng: 1.1533,
    plan: true, liens: []
  },
  {
    id: "bonaguil", n: "Château de Bonaguil", v: ["Bona Acucula"],
    t: "forteresse", sc: [13, 15, 16], per: "XIIIe s., transformation 1480-1520",
    arch: "Bérenger de Roquefeuil",
    prop: ["Famille de Roquefeuil", "Commune de Fumel"],
    ev: ["Chantier d'adaptation à l'artillerie sur quarante ans", "Vendu comme bien national en 1789"],
    desc: "Dernière grande forteresse médiévale française : donjon en proue, casemates, canonnières et enceinte adaptée à la poudre.",
    st: ["Gothique militaire", "Architecture de transition"], etat: "Partiellement ruiné",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Saint-Front-sur-Lémance", dep: "Lot-et-Garonne (47)", reg: "Quercy / Agenais", lat: 44.5433, lng: 0.9903,
    plan: true, liens: []
  },
  {
    id: "koenigsbourg", n: "Château du Haut-Kœnigsbourg", v: ["Burg Hohkönigsburg", "Staufenberg"],
    t: "château-fort", sc: [12, 15, 20], per: "1147, reconstruction 1900-1908",
    arch: "Bodo Ebhardt (reconstruction)",
    prop: ["Hohenstaufen", "Famille de Thierstein", "État français"],
    ev: ["Incendie par les Suédois en 1633", "Reconstruction offerte à Guillaume II en 1899"],
    desc: "Éperon de grès rose à 757 m : grand bastion, donjon carré et logis seigneurial restitués dans l'esprit du XVe siècle.",
    st: ["Gothique", "Reconstitution historiciste"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété départementale"], acc: "Ouvert au public",
    com: "Orschwiller", dep: "Bas-Rhin (67)", reg: "Alsace", lat: 48.2494, lng: 7.3444,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.chateau-hautkoenigsbourg.fr" }]
  },
  {
    id: "chantilly", n: "Château de Chantilly", v: ["Domaine de Chantilly"],
    t: "domaine", sc: [16, 19], per: "Petit Château 1560, Grand Château 1875-1882",
    arch: "Jean Bullant, Honoré Daumet (reconstruction)",
    prop: ["Famille de Montmorency", "Princes de Condé", "Institut de France"],
    ev: ["Démolition révolutionnaire du Grand Château", "Legs à l'Institut de France par le duc d'Aumale en 1886"],
    desc: "Château sur pièce d'eau, Grandes Écuries de Jean Aubert et parc de Le Nôtre ; abrite le musée Condé.",
    st: ["Renaissance", "Néo-Renaissance"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Chantilly", dep: "Oise (60)", reg: "Picardie / Valois", lat: 49.1936, lng: 2.4853,
    plan: true, liens: [{ label: "Site officiel", url: "https://chateaudechantilly.fr" }]
  },
  {
    id: "fontainebleau", n: "Château de Fontainebleau", v: ["Palais de Fontainebleau"],
    t: "palais", sc: [16, 17, 18], per: "XIIe s., refonte à partir de 1528",
    arch: "Gilles Le Breton, Primatice, Philibert Delorme",
    prop: ["Capétiens", "François Ier", "Napoléon Ier", "État français"],
    ev: ["Édit de Fontainebleau en 1685", "Abdication de Napoléon en 1814"],
    desc: "Suite de cours et de galeries de huit siècles : galerie François Ier, escalier en fer à cheval, appartements impériaux.",
    st: ["Renaissance", "Classique", "Empire"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Fontainebleau", dep: "Seine-et-Marne (77)", reg: "Île-de-France / Gâtinais", lat: 48.4022, lng: 2.6997,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.chateaudefontainebleau.fr" }]
  },
  {
    id: "cheverny", n: "Château de Cheverny", v: ["Cheverny"],
    t: "château", sc: [17], per: "1624 – 1630", arch: "Jacques Bougier",
    prop: ["Famille Hurault", "Marquis de Vibraye"],
    ev: ["Dépôt d'œuvres du Louvre en 1939", "Ouverture au public dès 1922"],
    desc: "Façade de pierre de Bourré d'une seule campagne, symétrie stricte, intérieurs Louis XIII conservés.",
    st: ["Classicisme Louis XIII"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Cheverny", dep: "Loir-et-Cher (41)", reg: "Sologne / Blésois", lat: 47.5003, lng: 1.4581,
    plan: false, liens: []
  },
  {
    id: "villandry", n: "Château de Villandry", v: ["Colombiers"],
    t: "château", sc: [16], per: "1532 – 1536", arch: "Jean Le Breton",
    prop: ["Jean Le Breton", "Marquis de Castellane", "Famille Carvallo"],
    ev: ["Signature de la paix des Colombiers en 1189", "Restitution des jardins Renaissance à partir de 1906"],
    desc: "Trois corps de logis en U autour d'une cour ouverte sur la vallée, donjon médiéval conservé, jardins en terrasses ordonnés.",
    st: ["Renaissance française"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Villandry", dep: "Indre-et-Loire (37)", reg: "Touraine", lat: 47.3403, lng: 0.5136,
    plan: true, liens: []
  },
  {
    id: "suscinio", n: "Château de Suscinio", v: ["Susinioc", "Château des ducs de Bretagne"],
    t: "château-fort", sc: [13, 15], per: "XIIIe – XVe s.", arch: "Ducs de Bretagne",
    prop: ["Ducs de Bretagne", "Département du Morbihan"],
    ev: ["Résidence de chasse ducale", "Carrière de pierre au XIXe s. avant sauvetage en 1965"],
    desc: "Plate-forme entourée de douves en eau face aux marais, six tours, pavements de terre cuite du XIVe siècle.",
    st: ["Gothique militaire breton"], etat: "Partiellement ruiné",
    stat: ["Monument historique classé", "Propriété départementale"], acc: "Ouvert au public",
    com: "Sarzeau", dep: "Morbihan (56)", reg: "Bretagne", lat: 47.5150, lng: -2.7000,
    plan: true, liens: []
  },
  {
    id: "peyrepertuse", n: "Château de Peyrepertuse", v: ["Petra Pertusa", "Citadelle du vertige"],
    t: "ruines", sc: [11, 13], per: "XIe s., extension royale 1250-1251",
    arch: "Chantier de Saint Louis (donjon Saint-Jordi)",
    prop: ["Comtes de Barcelone", "Couronne de France", "Commune de Duilhac"],
    ev: ["Reddition au roi de France en 1240", "Abandon après le traité des Pyrénées de 1659"],
    desc: "Crête calcaire de 300 m de long à 800 m d'altitude, deux châteaux reliés par l'escalier Saint-Louis taillé dans le roc.",
    st: ["Roman", "Militaire royal"], etat: "Ruines",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Duilhac-sous-Peyrepertuse", dep: "Aude (11)", reg: "Languedoc / Corbières", lat: 42.8697, lng: 2.5561,
    plan: true, liens: []
  },
  {
    id: "montsegur", n: "Château de Montségur", v: ["Montsegur", "Pog de Montségur"],
    t: "ruines", sc: [13], per: "Reconstruction après 1244", arch: "Guilhem de Peyrepertuse (place cathare)",
    prop: ["Comtes de Foix", "Couronne de France", "Commune de Montségur"],
    ev: ["Siège de dix mois et bûcher de 1244", "Fouilles archéologiques depuis 1964"],
    desc: "Enceinte polygonale sur un pog à 1207 m, donjon à citerne ; les vestiges visibles sont postérieurs au siège.",
    st: ["Militaire médiéval languedocien"], etat: "Ruines",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Montségur", dep: "Ariège (09)", reg: "Comté de Foix", lat: 42.8756, lng: 1.8322,
    plan: true, liens: []
  },
  {
    id: "coucy", n: "Château de Coucy", v: ["Coucy-le-Château-Auffrique"],
    t: "ruines", sc: [13], per: "1225 – 1242", arch: "Enguerrand III de Coucy",
    prop: ["Sires de Coucy", "Maison d'Orléans", "État français"],
    ev: ["Démantèlement partiel en 1652", "Donjon dynamité par l'armée allemande en 1917"],
    desc: "Le plus grand donjon d'Occident (54 m, 31 m de diamètre) réduit à sa base ; enceinte urbaine et basse-cour subsistantes.",
    st: ["Gothique militaire"], etat: "Ruines",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Coucy-le-Château-Auffrique", dep: "Aisne (02)", reg: "Picardie / Laonnois", lat: 49.5203, lng: 3.3236,
    plan: true, liens: []
  },
  {
    id: "loches", n: "Cité royale de Loches", v: ["Donjon de Loches", "Logis royal"],
    t: "forteresse", sc: [11, 15], per: "Donjon vers 1013, logis XVe s.",
    arch: "Foulques Nerra (donjon)",
    prop: ["Comtes d'Anjou", "Couronne de France", "Département d'Indre-et-Loire"],
    ev: ["Captivité de Ludovic Sforza", "Séjours de Jeanne d'Arc et d'Agnès Sorel"],
    desc: "Donjon rectangulaire de 36 m parmi les plus anciens conservés, logis royal gothique et flamboyant, enceinte urbaine complète.",
    st: ["Roman", "Gothique flamboyant"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété départementale"], acc: "Ouvert au public",
    com: "Loches", dep: "Indre-et-Loire (37)", reg: "Touraine", lat: 47.1272, lng: 0.9994,
    plan: true, liens: []
  },
  {
    id: "tarascon", n: "Château de Tarascon", v: ["Château du roi René"],
    t: "château-fort", sc: [15], per: "1400 – 1449", arch: "Chantier de Louis II et du roi René d'Anjou",
    prop: ["Maison d'Anjou", "État français", "Commune de Tarascon"],
    ev: ["Prison d'État de 1720 à 1926", "Graffitis de marins anglais dans les salles hautes"],
    desc: "Bloc quadrangulaire de pierre de taille les pieds dans le Rhône, terrasse sommitale unique et cour à galerie.",
    st: ["Gothique provençal"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Tarascon", dep: "Bouches-du-Rhône (13)", reg: "Provence", lat: 43.8060, lng: 4.6597,
    plan: true, liens: []
  },
  {
    id: "salses", n: "Forteresse de Salses", v: ["Fortaleza de Salses"],
    t: "forteresse", sc: [15], per: "1497 – 1503", arch: "Francisco Ramiro López",
    prop: ["Couronne d'Aragon", "Couronne de France", "État français"],
    ev: ["Siège franco-espagnol de 1639-1640", "Rattachement à la France en 1659"],
    desc: "Fortification semi-enterrée à murs de 10 m d'épaisseur : cas d'école du passage du château fort au bastion d'artillerie.",
    st: ["Militaire hispano-mauresque", "Transition artillerie"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Salses-le-Château", dep: "Pyrénées-Orientales (66)", reg: "Roussillon", lat: 42.8386, lng: 2.9169,
    plan: true, liens: []
  },
  {
    id: "murol", n: "Château de Murol", v: ["Murol-en-Auvergne"],
    t: "château-fort", sc: [12, 15], per: "XIIe – XVe s.", arch: "Famille de Murol, Guillaume de Sam",
    prop: ["Famille de Murol", "Famille d'Estaing", "Commune de Murol"],
    ev: ["Épargné à la Révolution par la protection de Lafayette", "Reconstitutions médiévales depuis 1985"],
    desc: "Basalte sur piton volcanique : enceinte polygonale, chapelle et logis Renaissance greffé au flanc sud.",
    st: ["Roman", "Gothique", "Renaissance"], etat: "Partiellement ruiné",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Murol", dep: "Puy-de-Dôme (63)", reg: "Auvergne", lat: 45.5772, lng: 2.9394,
    plan: false, liens: []
  },
  {
    id: "ango", n: "Manoir d'Ango", v: ["Manoir de Jehan Ango"],
    t: "manoir", sc: [16], per: "1530 – 1545", arch: "Commande de l'armateur Jean Ango",
    prop: ["Jean Ango", "Propriétaires privés successifs"],
    ev: ["Résidence d'été de l'armateur de François Ier", "Séjours d'artistes au XXe s."],
    desc: "Cour fermée de bâtiments à damiers de silex et brique, colombier monumental à coupole, loggia d'inspiration italienne.",
    st: ["Renaissance normande"], etat: "Bon état",
    stat: ["Monument historique classé", "Château privé"], acc: "Visite partielle",
    com: "Varengeville-sur-Mer", dep: "Seine-Maritime (76)", reg: "Normandie / Pays de Caux", lat: 49.9078, lng: 0.9989,
    plan: false, liens: []
  },
  {
    id: "boves", n: "Motte castrale de Boves", v: ["Castrum de Bova"],
    t: "motte castrale", sc: [10, 11, 13], per: "Xe – XIIIe s.", arch: "Seigneurs de Boves",
    prop: ["Seigneurs de Boves", "Commune de Boves"],
    ev: ["Fouilles programmées depuis 1996", "Abandon progressif après le XVe s."],
    desc: "Motte de terre de 20 m surmontée des vestiges d'une tour de pierre ; référence pour l'archéologie des mottes du nord de la France.",
    st: ["Fortification de terre"], etat: "Vestiges",
    stat: ["Monument historique inscrit", "Propriété communale"], acc: "Extérieurs uniquement",
    com: "Boves", dep: "Somme (80)", reg: "Picardie / Amiénois", lat: 49.8397, lng: 2.4033,
    plan: true, liens: []
  },
  {
    id: "tournoel", n: "Château de Tournoël", v: ["Tornoellum"],
    t: "ruines", sc: [12, 13], per: "XIIe – XIIIe s.", arch: "Comtes d'Auvergne",
    prop: ["Comtes d'Auvergne", "Famille de La Fayette", "Propriétaire privé"],
    ev: ["Prise par Guy de Dampierre pour Philippe Auguste en 1213", "Ruiné après un incendie au XVIIe s."],
    desc: "Donjon rond et donjon carré jumelés au-dessus de la Limagne, cuisine voûtée et courtines de basalte.",
    st: ["Roman", "Gothique"], etat: "Partiellement ruiné",
    stat: ["Monument historique classé", "Château privé"], acc: "Visite partielle",
    com: "Volvic", dep: "Puy-de-Dôme (63)", reg: "Auvergne / Limagne", lat: 45.8639, lng: 3.0464,
    plan: false, liens: []
  },
  {
    id: "blois", n: "Château royal de Blois", v: ["Blois", "Blesum castrum"],
    t: "château", sc: [13, 15, 16, 17], per: "XIIIe – XVIIe s.",
    arch: "Louis XII, François Ier, François Mansart (aile Gaston d'Orléans)",
    prop: ["Comtes de Blois", "Maison d'Orléans", "Commune de Blois"],
    ev: ["États généraux de 1576 et 1588", "Assassinat du duc de Guise en 1588"],
    desc: "Quatre ailes, quatre siècles autour d'une cour : gothique, brique et pierre Louis XII, escalier François Ier, façade classique.",
    st: ["Gothique", "Renaissance", "Classique"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Blois", dep: "Loir-et-Cher (41)", reg: "Blésois", lat: 47.5861, lng: 1.3306,
    plan: true, liens: []
  },
  {
    id: "reignac", n: "Maison forte de Reignac", v: ["Château de Reignac", "Reignac troglodytique"],
    t: "maison forte", sc: [14, 15, 16], per: "XIVe – XVIe s.", arch: "Seigneurs de Reignac, adaptation d'un abri sous roche",
    prop: ["Famille de Reignac", "Famille de Beynac", "Propriétaire privé"],
    ev: ["Occupation du site depuis la préhistoire", "Habitat seigneurial continu jusqu'au XIXe s.", "Ouverture à la visite en 2006"],
    desc: "Logis encastré dans la falaise de la Vézère : façade de pierre plaquée contre l'abri sous roche, salles troglodytiques, cuisine et chemin de ronde creusés dans le rocher.",
    st: ["Vernaculaire fortifié", "Troglodytique"], etat: "Intact / restauré",
    stat: ["Monument historique inscrit", "Château privé"], acc: "Ouvert au public",
    com: "Tursac", dep: "Dordogne (24)", reg: "Périgord noir", lat: 44.9628, lng: 1.0472,
    plan: false, liens: []
  },
  {
    id: "foix", n: "Château de Foix", v: ["Castèl de Fois"],
    t: "château-fort", sc: [11, 14, 15], per: "XIe – XVe s.", arch: "Comtes de Foix",
    prop: ["Comtes de Foix", "Couronne de France", "Département de l'Ariège"],
    ev: ["Siège de Simon de Montfort en 1211-1212", "Prison de 1862 à 1930"],
    desc: "Trois tours d'époques différentes sur un rocher dominant l'Ariège, reliées par des courtines étroites.",
    st: ["Roman", "Gothique"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété départementale"], acc: "Ouvert au public",
    com: "Foix", dep: "Ariège (09)", reg: "Comté de Foix", lat: 42.9661, lng: 1.6053,
    plan: true, liens: []
  },
  {
    id: "chinon", n: "Forteresse royale de Chinon", v: ["Château de Chinon", "Cité royale de Chinon"],
    t: "forteresse", sc: [12, 13, 15], per: "XIIe – XVe s., fossés secs creusés dès 1205",
    arch: "Chantier des Plantagenêt, extension de Philippe Auguste",
    prop: ["Comtes de Blois", "Plantagenêt", "Couronne de France", "Département d'Indre-et-Loire"],
    ev: ["Mort d'Henri II Plantagenêt en 1189", "Emprisonnement de dignitaires templiers en 1308", "Rencontre de Jeanne d'Arc et de Charles VII en 1429"],
    desc: "Éperon rocheux dominant la Vienne, structuré en trois châteaux distincts séparés par des douves sèches : fort du Coudray, château du Milieu et fort Saint-Georges.",
    st: ["Militaire médiéval", "Gothique"], etat: "Partiellement ruiné",
    stat: ["Monument historique classé", "Propriété départementale"], acc: "Ouvert au public",
    com: "Chinon", dep: "Indre-et-Loire (37)", reg: "Touraine", lat: 47.1681, lng: 0.2361,
    plan: true, liens: []
  },
  {
    id: "saumur", n: "Château de Saumur", v: ["Château des ducs d'Anjou"],
    t: "château", sc: [10, 14, 15], per: "Xe s., reconstruction par Louis Ier d'Anjou 1367-1370",
    arch: "Louis Ier d'Anjou, remaniements de René d'Anjou",
    prop: ["Comtes de Blois", "Ducs d'Anjou", "Couronne de France", "Commune de Saumur"],
    ev: ["Prise sur Jean sans Terre par Philippe Auguste en 1203", "Résidence de René d'Anjou au XVe s.", "Classement monument historique en 1862"],
    desc: "Silhouette à tourelles sur la Loire popularisée par les Très Riches Heures du duc de Berry ; enceinte pentagonale et logis remaniés par les ducs d'Anjou.",
    st: ["Gothique", "Renaissance angevine"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété communale", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Saumur", dep: "Maine-et-Loire (49)", reg: "Anjou", lat: 47.2570, lng: -0.0724,
    plan: true, liens: []
  },
  {
    id: "sully", n: "Château de Sully-sur-Loire", v: ["Château de Sully"],
    t: "château", sc: [12, 14, 17], per: "Mentionné en 1102, reconstruction 1396-1409",
    arch: "Raymond du Temple, pour Gui VI de La Trémoille et Marie de Sully",
    prop: ["Seigneurs de Sully", "Famille de La Trémoille", "Maximilien de Béthune, duc de Sully"],
    ev: ["Reconstruction lancée par Gui VI de La Trémoille en 1396", "Acquisition par le ministre d'Henri IV en 1602", "Exil de Voltaire chez le duc de Sully en 1716"],
    desc: "Donjon quadrangulaire cantonné de tours rondes posé au bord de la Loire, douves alimentées par la Sange et logis en retour d'équerre.",
    st: ["Gothique militaire", "Renaissance"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété départementale"], acc: "Ouvert au public",
    com: "Sully-sur-Loire", dep: "Loiret (45)", reg: "Orléanais", lat: 47.7677, lng: 2.3752,
    plan: true, liens: []
  },
  {
    id: "vauxlevicomte", n: "Château de Vaux-le-Vicomte", v: [],
    t: "château", sc: [17], per: "1658 – 1661",
    arch: "Louis Le Vau, Charles Le Brun (décors), André Le Nôtre (jardins)",
    prop: ["Nicolas Fouquet", "Maréchal de Villars", "Famille Sommier", "Marquis de Vogüé"],
    ev: ["Fête donnée à Louis XIV le 17 août 1661, suivie de l'arrestation de Fouquet", "Rachat et restauration par Alfred Sommier en 1875", "Modèle direct du chantier de Versailles"],
    desc: "Chef-d'œuvre du classicisme réunissant pour la première fois Le Vau, Le Brun et Le Nôtre ; logis entouré de douves et jardins en perspective absolue.",
    st: ["Classicisme français"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Maincy", dep: "Seine-et-Marne (77)", reg: "Île-de-France / Brie", lat: 48.5659, lng: 2.7141,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.vaux-le-vicomte.com" }]
  },
  {
    id: "sedan", n: "Château de Sedan", v: ["Château-haut de Sedan"],
    t: "forteresse", sc: [15, 16, 17], per: "1424 – 1690, agrandissements successifs",
    arch: "Princes de la Marck, ducs de Bouillon",
    prop: ["Princes de la Marck", "Ducs de Bouillon (La Tour d'Auvergne)", "Couronne de France", "Commune de Sedan"],
    ev: ["Naissance de Turenne au château en 1611", "Intégration au pré carré fortifié de Louis XIV", "Classement monument historique en 1965"],
    desc: "Plus grand château fort d'Europe par sa surface bâtie : éperon rocheux hérissé de bastions successifs dominant la Meuse.",
    st: ["Militaire médiéval", "Fortification bastionnée"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Sedan", dep: "Ardennes (08)", reg: "Grand Est / Ardennes", lat: 49.7019, lng: 4.9494,
    plan: true, liens: []
  },
  {
    id: "falaise", n: "Château de Falaise", v: ["Château Guillaume-le-Conquérant"],
    t: "château-fort", sc: [10, 12, 13], per: "Xe s., donjon d'Henri Ier Beauclerc vers 1123",
    arch: "Ducs de Normandie",
    prop: ["Ducs de Normandie", "Couronne de France", "Commune de Falaise"],
    ev: ["Naissance de Guillaume le Conquérant vers 1027-1028", "Prise par Philippe Auguste en 1204", "Restauration contemporaine après les bombardements de 1944"],
    desc: "Éperon schisteux dominant la ville : donjon roman d'Henri Ier Beauclerc, tour Talbot cylindrique du XIIIe siècle et courtines reliant les deux ouvrages.",
    st: ["Roman", "Gothique militaire"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Falaise", dep: "Calvados (14)", reg: "Normandie", lat: 48.8932, lng: -0.2039,
    plan: false, liens: []
  },
  {
    id: "josselin", n: "Château de Josselin", v: [],
    t: "château-fort", sc: [11, 15], per: "XIe s., façade sur cour 1490-1505",
    arch: "Ducs de Rohan",
    prop: ["Seigneurs de Josselin", "Maison de Rohan"],
    ev: ["Combat des Trente livré à proximité en 1351", "Classement monument historique le 21 août 1928", "Résidence ininterrompue des Rohan depuis sa construction"],
    desc: "Façade défensive à trois tours rondes côté rivière, contrastant avec une façade sur cour finement sculptée de style gothique flamboyant.",
    st: ["Militaire médiéval breton", "Gothique flamboyant"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Josselin", dep: "Morbihan (56)", reg: "Bretagne", lat: 47.9522, lng: -2.5472,
    plan: false, liens: []
  },
  {
    id: "kerjean", n: "Château de Kerjean", v: ["Forteresse de Kerjean"],
    t: "château", sc: [16], per: "1566 – 1595",
    arch: "Louis Barbier, seigneur de Kerjean",
    prop: ["Famille Barbier de Kerjean", "État français"],
    ev: ["Vente comme bien national à la Révolution, mobilier dispersé", "Acquisition par l'État en 1911", "Classement monument historique le 29 avril 1911"],
    desc: "Manoir fortifié du pays de Léon : enceinte bastionnée, colombier monumental et logis Renaissance à lucarnes sculptées.",
    st: ["Renaissance bretonne"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Saint-Vougay", dep: "Finistère (29)", reg: "Bretagne", lat: 48.5806, lng: -4.1472,
    plan: false, liens: []
  },
  {
    id: "lalatte", n: "Fort la Latte", v: ["Château de la Roche Goyon"],
    t: "château-fort", sc: [13, 17], per: "XIIIe s., refonte pour l'artillerie au XVIIe s.",
    arch: "Seigneurs Goyon-Matignon",
    prop: ["Famille Goyon-Matignon", "Propriétaire privé"],
    ev: ["Classements monument historique en 1925 et 1934", "Décor de tournage pour plusieurs films dont Les Vikings en 1958"],
    desc: "Deux enceintes successives sur un cap rocheux battu par la mer, reliées par un pont-levis double au-dessus d'une crevasse naturelle.",
    st: ["Militaire médiéval", "Fortification côtière"], etat: "Bon état",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Plévenon", dep: "Côtes-d'Armor (22)", reg: "Bretagne", lat: 48.6683, lng: -2.2847,
    plan: false, liens: []
  },
  {
    id: "roquetaillade", n: "Château de Roquetaillade", v: ["Château neuf de Roquetaillade"],
    t: "château-fort", sc: [12, 14, 19], per: "XIIe s., château neuf 1306, restauration 1867-1870",
    arch: "Cardinal Gaillard de La Mothe (château neuf), Eugène Viollet-le-Duc (décors)",
    prop: ["Famille de La Mothe", "Famille de Mauvezin de La Mothe"],
    ev: ["Classement parmi la première liste des monuments historiques de 1840", "Décors intérieurs confiés à Viollet-le-Duc", "Ouverture au public en 1956"],
    desc: "Deux châteaux dans une même enceinte fortifiée : le vieux château du XIIe siècle et le château neuf du XIVe, dont Viollet-le-Duc a orné les intérieurs.",
    st: ["Militaire médiéval", "Restauration du XIXe s."], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Mazères", dep: "Gironde (33)", reg: "Gascogne / Bordelais", lat: 44.4925, lng: -0.2697,
    plan: true, liens: []
  },
  {
    id: "if", n: "Château d'If", v: ["Forteresse d'If"],
    t: "forteresse", sc: [16], per: "1529 – 1531", arch: "Chantier de François Ier",
    prop: ["François Ier", "Couronne de France", "État français"],
    ev: ["Prison d'État pendant environ 400 ans", "Cadre du Comte de Monte-Cristo d'Alexandre Dumas", "Classement monument historique en 1926"],
    desc: "Bloc carré de trois étages flanqué de tours d'angle casematées sur un îlot du Frioul, enceinte bastionnée dominant la rade de Marseille.",
    st: ["Fortification bastionnée"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État", "Parc national des Calanques"], acc: "Ouvert au public",
    com: "Marseille", dep: "Bouches-du-Rhône (13)", reg: "Provence", lat: 43.2797, lng: 5.3253,
    plan: true, liens: []
  },
  {
    id: "avignon", n: "Palais des papes d'Avignon", v: ["Palais des Papes"],
    t: "palais", sc: [14], per: "1335 – 1370", arch: "Pierre Poisson, Jean de Louvres",
    prop: ["Papauté", "État français", "Ville d'Avignon"],
    ev: ["Six conclaves tenus entre 1334 et 1394", "Résidence de sept papes durant l'Avignon pontificale", "Caserne puis prison après la Révolution"],
    desc: "Plus grand édifice gothique du Moyen Âge, imbrication du palais vieux fortifié de Benoît XII et du palais neuf fastueux de Clément VI.",
    st: ["Gothique international"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété communale", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Avignon", dep: "Vaucluse (84)", reg: "Provence / Comtat Venaissin", lat: 43.9508, lng: 4.8075,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.palais-des-papes.com" }]
  },
  {
    id: "val", n: "Château de Val", v: [],
    t: "château-fort", sc: [13, 15], per: "Fondations XIIIe s., château actuel vers 1428-1450",
    arch: "Guillaume IV d'Estaing",
    prop: ["Famille de Pierrefort", "Famille d'Estaing", "Commune de Bort-les-Orgues"],
    ev: ["Achat et reconstruction par Guillaume IV d'Estaing au XVe s.", "Mise en eau du lac de retenue du barrage de Bort en 1952"],
    desc: "Six tours à poivrière groupées autour d'un logis, devenu presqu'île depuis la mise en eau du lac de retenue du barrage de Bort.",
    st: ["Gothique militaire auvergnat"], etat: "Bon état",
    stat: ["Monument historique inscrit", "Propriété communale"], acc: "Ouvert au public",
    com: "Lanobre", dep: "Cantal (15)", reg: "Auvergne", lat: 45.4428, lng: 2.5053,
    plan: false, liens: []
  },
  {
    id: "bussyrabutin", n: "Château de Bussy-Rabutin", v: ["Château de Bussy-le-Grand"],
    t: "château", sc: [12, 14, 17], per: "Fondations XIIe-XIVe s., décors 1660-1700",
    arch: "Roger de Rabutin, comte de Bussy",
    prop: ["Famille de Rabutin", "État français"],
    ev: ["Exil du comte de Bussy à partir de 1666 après la publication de l'Histoire amoureuse des Gaules", "Décoration des galeries durant son exil", "Acquisition par l'État en 1929"],
    desc: "Façade Renaissance sur cour dissimulant des galeries peintes que le comte de Bussy fit décorer de portraits satiriques durant son exil.",
    st: ["Renaissance", "Décor classique"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Bussy-le-Grand", dep: "Côte-d'Or (21)", reg: "Bourgogne", lat: 47.5614, lng: 4.5236,
    plan: false, liens: []
  },
  {
    id: "beaucaire", n: "Château de Beaucaire", v: [],
    t: "ruines", sc: [11, 13], per: "XIe s., citadelle sous Saint Louis",
    arch: "Comtes de Toulouse, chantier royal capétien",
    prop: ["Comtes de Toulouse", "Couronne de France", "Commune de Beaucaire"],
    ev: ["Siège de 1216 pendant la croisade albigeoise", "Traité de Beaucaire en 1251", "Démantèlement ordonné par Richelieu en 1632"],
    desc: "Ruines d'une citadelle capétienne face à Tarascon sur l'autre rive du Rhône, tour polygonale à triangle caractéristique et éperon rocheux dominant la ville.",
    st: ["Militaire médiéval", "Gothique"], etat: "Ruines",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Beaucaire", dep: "Gard (30)", reg: "Provence / Languedoc", lat: 43.8098, lng: 4.6451,
    plan: false, liens: []
  },
  {
    id: "nantes", n: "Château des ducs de Bretagne", v: ["Château de Nantes"],
    t: "forteresse", sc: [14, 15, 18], per: "Principalement XVe s., éléments du XIVe au XVIIIe s.",
    arch: "Duc François II, achevé par Anne de Bretagne",
    prop: ["Ducs de Bretagne", "Couronne de France", "Commune de Nantes"],
    ev: ["Naissance d'Anne de Bretagne au château vers 1477", "Rattachement du duché au domaine royal en 1532", "Cession à la ville de Nantes en 1915"],
    desc: "Enceinte pentagonale de sept tours entourée de douves sèches en plein centre-ville, mêlant grand logis gothique et corps de bâtiment Renaissance.",
    st: ["Gothique", "Renaissance"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Nantes", dep: "Loire-Atlantique (44)", reg: "Bretagne / Pays de la Loire", lat: 47.2156, lng: -1.5497,
    plan: true, liens: []
  },
  {
    id: "brissac", n: "Château de Brissac", v: ["Château de Brissac-Loire-Aubance"],
    t: "château", sc: [11, 16, 17], per: "XIe s., surélévation par les Cossé-Brissac au XVIIe s.",
    arch: "Familles de Brissac",
    prop: ["Comtes d'Anjou", "Famille de Cossé-Brissac"],
    ev: ["Rachat par Charles II de Cossé-Brissac en 1502", "Construction du corps de logis à sept étages au XVIIe s., resté inachevé", "Résidence ininterrompue des ducs de Brissac"],
    desc: "Deux tourelles médiévales encadrant un corps de logis classique de sept étages, resté inachevé : le plus haut château de France.",
    st: ["Militaire médiéval", "Classicisme français"], etat: "Intact / restauré",
    stat: ["Monument historique inscrit", "Château privé"], acc: "Ouvert au public",
    com: "Brissac Loire Aubance", dep: "Maine-et-Loire (49)", reg: "Anjou", lat: 47.3528, lng: -0.4498,
    plan: false, liens: []
  },
  {
    id: "tiffauges", n: "Château de Tiffauges", v: ["Château de Barbe-Bleue"],
    t: "ruines", sc: [13, 15], per: "XIIIe s., résidence de Gilles de Rais 1420-1440",
    arch: "Seigneurs de Tiffauges",
    prop: ["Seigneurs de Tiffauges", "Gilles de Rais", "Commune de Tiffauges"],
    ev: ["Résidence de Gilles de Rais, compagnon de Jeanne d'Arc, avant son procès de 1440", "Démantèlement partiel après la Révolution"],
    desc: "Vastes ruines sur un éperon dominant la Sèvre nantaise : donjon, tour du vidame et logis attribués au surnom de « château de Barbe-Bleue ».",
    st: ["Militaire médiéval"], etat: "Ruines",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Tiffauges", dep: "Vendée (85)", reg: "Pays de la Loire", lat: 47.0164, lng: -1.1147,
    plan: false, liens: []
  },
  {
    id: "pau", n: "Château de Pau", v: [],
    t: "château", sc: [12, 14, 19], per: "XIIe – XIXe s., renforcement par Gaston Fébus fin XIVe s.",
    arch: "Vicomtes de Béarn, Gaston Fébus",
    prop: ["Vicomtes de Béarn", "Maison d'Albret", "Henri IV", "État français"],
    ev: ["Naissance d'Henri IV au château en 1553", "Restauration pour Louis-Philippe au XIXe s.", "Ouverture du musée national en 1927"],
    desc: "Château médiéval de brique et de galets renforcé par Gaston Fébus, agrandi et redécoré au XIXe siècle pour célébrer la naissance d'Henri IV.",
    st: ["Militaire médiéval béarnais", "Restauration du XIXe s."], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Pau", dep: "Pyrénées-Atlantiques (64)", reg: "Béarn", lat: 43.2947, lng: -0.3750,
    plan: true, liens: []
  },
  {
    id: "larochefoucauld", n: "Château de La Rochefoucauld", v: [],
    t: "château", sc: [11, 16], per: "Forteresse du XIe s., reconstruction Renaissance vers 1520",
    arch: "Famille de La Rochefoucauld",
    prop: ["Famille de La Rochefoucauld"],
    ev: ["Conservation des tours de la forteresse féodale dans la reconstruction Renaissance", "Classement monument historique en 1955", "Propriété ininterrompue de la même famille depuis sa fondation"],
    desc: "Escalier Renaissance à cage ouverte de style italien greffé sur les tours d'une forteresse féodale du XIe siècle, autour d'une cour à galeries superposées.",
    st: ["Militaire médiéval", "Renaissance"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "La Rochefoucauld-en-Angoumois", dep: "Charente (16)", reg: "Angoumois", lat: 45.7466, lng: 0.3806,
    plan: false, liens: []
  },
  {
    id: "oiron", n: "Château d'Oiron", v: ["Château d'Oyron"],
    t: "château", sc: [16, 17], per: "Chantier de la famille Gouffier, XVIe – XVIIe s.",
    arch: "Famille Gouffier",
    prop: ["Famille Gouffier", "État français"],
    ev: ["Classement monument historique en 1923", "Acquisition par l'État en 1946", "Installation d'une collection d'art contemporain"],
    desc: "Galerie peinte évoquant les exploits légendaires de la famille Gouffier, aile Renaissance et communs classiques autour d'une cour d'honneur.",
    st: ["Renaissance", "Classicisme"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Plaine-et-Vallées", dep: "Deux-Sèvres (79)", reg: "Poitou", lat: 46.9517, lng: -0.0775,
    plan: false, liens: []
  },
  {
    id: "nerac", n: "Château de Nérac", v: [],
    t: "château", sc: [15, 16], per: "Style Louis XII, achevé sous Jeanne d'Albret",
    arch: "Maison d'Albret",
    prop: ["Maison d'Albret", "Couronne de France", "Commune de Nérac"],
    ev: ["Cour de Jeanne d'Albret et d'Henri de Navarre", "Démantèlement à la Révolution", "Classement de l'aile subsistante en 1862"],
    desc: "Seule aile subsistante d'un vaste château Renaissance sur la Baïse, galerie à arcades superposées de transition entre gothique et Première Renaissance.",
    st: ["Gothique", "Première Renaissance"], etat: "Partiellement ruiné",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Nérac", dep: "Lot-et-Garonne (47)", reg: "Gascogne / Albret", lat: 44.1353, lng: 0.3400,
    plan: false, liens: []
  },
  {
    id: "grignan", n: "Château de Grignan", v: [],
    t: "château", sc: [12, 13, 16], per: "XIIe s., forteresse XIIIe s., façade Renaissance XVIe s.",
    arch: "Famille d'Adhémar de Monteil",
    prop: ["Famille d'Adhémar", "Famille de Castellane", "Commune de Grignan"],
    ev: ["Résidence de Madame de Sévigné lors de ses séjours chez sa fille dès 1670", "Destructions révolutionnaires puis incendie de 1936", "Restauration au XXe s."],
    desc: "Piton rocheux dominant la Drôme provençale : façade Renaissance à loggia superposée sur un noyau féodal remanié en forteresse.",
    st: ["Militaire médiéval", "Renaissance"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété départementale"], acc: "Ouvert au public",
    com: "Grignan", dep: "Drôme (26)", reg: "Drôme provençale", lat: 44.4187, lng: 4.9092,
    plan: false, liens: []
  },
  {
    id: "annecy", n: "Château d'Annecy", v: [],
    t: "château-fort", sc: [12, 15, 16], per: "XIIe s., remaniements 1430-1571",
    arch: "Comtes de Genève, ducs de Savoie-Nemours",
    prop: ["Comtes de Genève", "Ducs de Savoie-Nemours", "Commune d'Annecy"],
    ev: ["Résidence des ducs de Genevois-Nemours au XVIe s.", "Acquisition par la ville en 1953", "Transformation en musée"],
    desc: "Ensemble de logis successifs autour d'une cour, dominant la vieille ville et le lac d'Annecy depuis son éperon rocheux.",
    st: ["Militaire médiéval savoyard", "Renaissance"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Annecy", dep: "Haute-Savoie (74)", reg: "Savoie", lat: 45.8975, lng: 6.1264,
    plan: false, liens: []
  },
  {
    id: "chambery", n: "Château des ducs de Savoie", v: ["Château de Chambéry"],
    t: "château-fort", sc: [11, 13], per: "XIe s., agrandissements dès le XIIIe s.",
    arch: "Comtes puis ducs de Savoie",
    prop: ["Comtes de Savoie", "Ducs de Savoie", "Département de la Savoie"],
    ev: ["Dépôt du Saint Suaire dans la chapelle de 1502 à 1578", "Classement monument historique en 1881", "Installation de la préfecture de la Savoie"],
    desc: "Ancienne résidence des comtes puis ducs de Savoie autour d'une cour intérieure, sainte chapelle gothique et grand carillon de 70 cloches.",
    st: ["Militaire médiéval", "Gothique"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété départementale"], acc: "Visite partielle",
    com: "Chambéry", dep: "Savoie (73)", reg: "Savoie", lat: 45.5644, lng: 5.9178,
    plan: false, liens: []
  },
  {
    id: "sisteron", n: "Citadelle de Sisteron", v: [],
    t: "forteresse", sc: [13, 16, 17], per: "Fortifications médiévales, refonte par Jean Errard puis Vauban",
    arch: "Jean Errard, Vauban",
    prop: ["Couronne de France", "Commune de Sisteron"],
    ev: ["Renforcement par Jean Errard, ingénieur d'Henri IV", "Consolidation par Vauban à la fin du XVIIe s.", "Bombardements de 1944"],
    desc: "Éperon rocheux verrouillant le passage entre Dauphiné et Provence, fortifications superposées de l'époque médiévale à Vauban dominant la Durance.",
    st: ["Militaire médiéval", "Fortification bastionnée"], etat: "Bon état",
    stat: ["Monument historique classé"], acc: "Ouvert au public",
    com: "Sisteron", dep: "Alpes-de-Haute-Provence (04)", reg: "Provence", lat: 44.1989, lng: 5.9431,
    plan: true, liens: []
  },
  {
    id: "baux", n: "Château des Baux-de-Provence", v: ["Château des Baux"],
    t: "ruines", sc: [11, 13], per: "XIe – XIIIe s., apogée sous les seigneurs des Baux",
    arch: "Seigneurs des Baux",
    prop: ["Seigneurs des Baux", "Comtes de Provence", "Couronne de France", "Commune des Baux-de-Provence"],
    ev: ["Guerre des Baux (1424-1426) contre la maison d'Anjou", "Démantèlement ordonné par Richelieu en 1633", "Ouverture au public au XXe s."],
    desc: "Château fort taillé dans le rocher des Alpilles, courtines et tour éventrée dominant un vaste panorama sur la plaine de la Crau.",
    st: ["Militaire médiéval provençal"], etat: "Ruines",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Les Baux-de-Provence", dep: "Bouches-du-Rhône (13)", reg: "Provence / Alpilles", lat: 43.7443, lng: 4.7971,
    plan: true, liens: []
  },
  {
    id: "bonifacio", n: "Citadelle de Bonifacio", v: [],
    t: "enceinte fortifiée", sc: [12, 16], per: "Fin XIIe s., fortification continue jusqu'au XVIe s.",
    arch: "République de Gênes",
    prop: ["République de Gênes", "Couronne de France", "Commune de Bonifacio"],
    ev: ["Premier préside génois de Corse, fin du XIIe s.", "Sièges répétés dont celui d'Alphonse V d'Aragon en 1420", "Rattachement de la Corse à la France en 1768"],
    desc: "Ville haute fortifiée sur un plateau calcaire dominant la mer de 60 mètres de haut, verrouillant les bouches de Bonifacio entre Corse et Sardaigne.",
    st: ["Fortification génoise"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Bonifacio", dep: "Corse-du-Sud (2A)", reg: "Corse", lat: 41.3878, lng: 9.1595,
    plan: false, liens: []
  },
  {
    id: "luneville", n: "Château de Lunéville", v: ["Versailles lorrain"],
    t: "palais", sc: [18], per: "1703 – 1720",
    arch: "Germain Boffrand, Pierre Bourdict, Nicolas Dorbay",
    prop: ["Ducs de Lorraine", "Stanislas Leszczyński", "Commune de Lunéville"],
    ev: ["Résidence principale du duc Léopold Ier jusqu'à sa mort en 1729", "Mort accidentelle de Stanislas Leszczyński en 1766", "Incendie majeur en 2003, restauration depuis"],
    desc: "Palais ducal inspiré de Versailles, aile unique restée dissymétrique faute de moyens, entouré de jardins à la française.",
    st: ["Classicisme français"], etat: "Partiellement ruiné",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Visite partielle",
    com: "Lunéville", dep: "Meurthe-et-Moselle (54)", reg: "Lorraine", lat: 48.5947, lng: 6.4917,
    plan: true, liens: []
  },
  {
    id: "hautbarr", n: "Château du Haut-Barr", v: ["L'Œil de l'Alsace"],
    t: "ruines", sc: [12], per: "Fondation attribuée au XIIe s.",
    arch: "Évêques de Strasbourg",
    prop: ["Évêques de Strasbourg", "Commune de Saverne"],
    ev: ["Résidence de repli des princes-évêques de Strasbourg", "Classement monument historique en 1874"],
    desc: "Trois éperons rocheux reliés par des passerelles, dominant la plaine d'Alsace et le col de Saverne d'où son surnom d'« Œil de l'Alsace ».",
    st: ["Militaire médiéval"], etat: "Ruines",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Saverne", dep: "Bas-Rhin (67)", reg: "Alsace", lat: 48.7250, lng: 7.3386,
    plan: false, liens: []
  },
  {
    id: "bazoches", n: "Château de Bazoches", v: [],
    t: "château", sc: [12, 17], per: "XIIe s., aménagements par Vauban à la fin du XVIIe s.",
    arch: "Sébastien Le Prestre de Vauban",
    prop: ["Seigneurs de Bazoches", "Maréchal de Vauban", "Descendants de Vauban"],
    ev: ["Acquisition par Vauban en 1675", "Vauban y prépare ses campagnes de siège", "Classement monument historique en 1994"],
    desc: "Logis médiéval remanié par Vauban en demeure de maréchal, cabinet de travail et collections liées à ses campagnes conservés.",
    st: ["Militaire médiéval", "Classicisme"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Bazoches", dep: "Nièvre (58)", reg: "Bourgogne / Morvan", lat: 47.3808, lng: 3.7950,
    plan: false, liens: []
  },
  {
    id: "cormatin", n: "Château de Cormatin", v: [],
    t: "château", sc: [17], per: "Début du XVIIe s.",
    arch: "Chantier pour Antoine du Blé d'Huxelles",
    prop: ["Famille du Blé d'Huxelles", "Propriétaires privés successifs"],
    ev: ["Décor intérieur Louis XIII conservé quasiment intact", "Ouverture au public parmi les châteaux de Bourgogne du Sud"],
    desc: "Escalier « vide à la moderne » et cabinets peints Louis XIII exceptionnellement conservés, château posé sur une île de la Grosne.",
    st: ["Classicisme Louis XIII"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Cormatin", dep: "Saône-et-Loire (71)", reg: "Bourgogne", lat: 46.5431, lng: 4.6843,
    plan: false, liens: []
  },
  {
    id: "ancyfranc", n: "Château d'Ancy-le-Franc", v: [],
    t: "château", sc: [16], per: "1538 – 1546", arch: "Sebastiano Serlio",
    prop: ["Antoine III de Clermont-Tonnerre", "Propriétaires privés successifs"],
    ev: ["Une des premières réalisations de la Seconde Renaissance française", "Classements monument historique en 1983 et 2003"],
    desc: "Plan carré à quatre ailes égales autour d'une cour, façades à ordres superposés : jalon de l'architecture modulaire de la Renaissance française.",
    st: ["Seconde Renaissance française"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Ancy-le-Franc", dep: "Yonne (89)", reg: "Bourgogne", lat: 47.7741, lng: 4.1618,
    plan: true, liens: []
  },
  {
    id: "besancon", n: "Citadelle de Besançon", v: [],
    t: "enceinte fortifiée", sc: [17, 18], per: "1668 – 1711", arch: "Sébastien Le Prestre de Vauban",
    prop: ["Couronne de France", "Commune de Besançon"],
    ev: ["Première pierre posée en 1668, alors possession espagnole", "Classements monument historique de 1942 à 2025", "Inscription au patrimoine mondial UNESCO en 2008"],
    desc: "Onze hectares fortifiés au sommet du mont Saint-Étienne, verrouillant le méandre du Doubs : chef-d'œuvre de Vauban parmi les douze sites UNESCO de son réseau.",
    st: ["Fortification bastionnée"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété communale", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Besançon", dep: "Doubs (25)", reg: "Franche-Comté", lat: 47.2314, lng: 6.0325,
    plan: true, liens: []
  },
  {
    id: "rambures", n: "Château de Rambures", v: [],
    t: "château-fort", sc: [15, 17, 19], per: "XVe s., démantelé au XVIIe s., restauré au XIXe s.",
    arch: "Seigneurs de Rambures",
    prop: ["Famille de Rambures"],
    ev: ["Un des rares châteaux médiévaux subsistants de la Somme", "Démantèlement partiel au XVIIe s.", "Classement monument historique en 1927"],
    desc: "Plan en losange à tours rondes de brique et silex, chef-d'œuvre de l'architecture militaire médiévale tardive adaptée aux premières bombardes.",
    st: ["Gothique militaire tardif"], etat: "Bon état",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Rambures", dep: "Somme (80)", reg: "Picardie / Vimeu", lat: 49.9446, lng: 1.7074,
    plan: false, liens: []
  },
  {
    id: "hardelot", n: "Château d'Hardelot", v: [],
    t: "château-fort", sc: [13, 19], per: "Fondations de 1222, manoir actuel achevé au milieu du XIXe s.",
    arch: "Reconstruction du XIXe s. sur fondations médiévales",
    prop: ["Seigneurs d'Hardelot", "Propriétaires privés successifs", "Commune de Condette"],
    ev: ["Fondation en 1222", "Reconstruction en manoir néogothique au XIXe s.", "Centre culturel de l'Entente cordiale depuis les années 2010"],
    desc: "Polygone à neuf tours entouré de deux fossés concentriques, dominant les marécages et le lac des Miroirs près du littoral.",
    st: ["Néogothique du XIXe s."], etat: "Intact / restauré",
    stat: ["Monument historique inscrit", "Propriété communale"], acc: "Ouvert au public",
    com: "Condette", dep: "Pas-de-Calais (62)", reg: "Côte d'Opale", lat: 50.6457, lng: 1.6115,
    plan: false, liens: []
  },
  {
    id: "fere", n: "Château de Fère-en-Tardenois", v: [],
    t: "ruines", sc: [13], per: "Début du XIIIe s.",
    arch: "Seigneurs de Fère, galerie ajoutée par Anne de Montmorency",
    prop: ["Seigneurs de Fère", "Connétable Anne de Montmorency"],
    ev: ["Ajout d'une galerie Renaissance sur pont enjambant les douves au XVIe s.", "Protection partielle au titre des monuments historiques"],
    desc: "Ruines d'un château fort du XIIIe siècle prolongées par une galerie Renaissance juchée sur un pont à cinq arches, unique en France.",
    st: ["Militaire médiéval", "Renaissance"], etat: "Ruines",
    stat: ["Monument historique inscrit"], acc: "Extérieurs uniquement",
    com: "Fère-en-Tardenois", dep: "Aisne (02)", reg: "Picardie / Tardenois", lat: 49.2222, lng: 3.5321,
    plan: false, liens: []
  },
  {
    id: "carrouges", n: "Château de Carrouges", v: [],
    t: "château", sc: [14, 16, 18], per: "XIVe s., remaniements aux XVIe et XVIIIe s.",
    arch: "Famille Le Veneur",
    prop: ["Famille de Carrouges", "Famille Le Veneur", "État français"],
    ev: ["Pavillon ajouté par le cardinal Le Veneur au XVIe s.", "Bastion fortifié pendant les guerres de Religion", "Restauration après les dommages de 1944"],
    desc: "Logis de brique rose cerné de douves en eau, pavillon d'entrée Renaissance et grands appartements des XVIIe-XVIIIe siècles.",
    st: ["Gothique", "Renaissance", "Classicisme"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Carrouges", dep: "Orne (61)", reg: "Normandie", lat: 48.5601, lng: -0.1544,
    plan: false, liens: []
  },
  {
    id: "caen", n: "Château de Caen", v: ["Château de Guillaume le Conquérant"],
    t: "château-fort", sc: [11], per: "Fondé vers 1060", arch: "Guillaume le Conquérant",
    prop: ["Ducs de Normandie", "Couronne de France", "Commune de Caen"],
    ev: ["Fondation par Guillaume le Conquérant vers 1060", "Résidence ducale puis royale au Moyen Âge", "Reconstruction des musées après les bombardements de 1944"],
    desc: "Un des plus grands châteaux forts d'Europe avec ses 5,5 hectares intra-muros, donjon disparu et logis ducal du XIIe siècle conservé.",
    st: ["Militaire médiéval anglo-normand"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Caen", dep: "Calvados (14)", reg: "Normandie", lat: 49.1864, lng: -0.3628,
    plan: true, liens: []
  },
  {
    id: "rambouillet", n: "Château de Rambouillet", v: [],
    t: "domaine", sc: [14, 18], per: "Tour du XIVe s., corps de logis remanié au XVIIIe s.",
    arch: "Remaniements successifs pour la Couronne",
    prop: ["Famille d'Angennes", "Louis XVI", "État français"],
    ev: ["Mort de François Ier au château en 1547", "Premier sommet du G6 en 1975", "Résidence de chasse présidentielle jusqu'en 2009"],
    desc: "Tour médiévale, corps de logis du XVIIIe siècle et laiterie de la reine, au cœur d'un domaine forestier de 980 hectares.",
    st: ["Gothique", "Classicisme"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Visite partielle",
    com: "Rambouillet", dep: "Yvelines (78)", reg: "Île-de-France", lat: 48.6456, lng: 1.8178,
    plan: true, liens: []
  }
];
