/* Jeu de données de démonstration — 35 châteaux réels, coordonnées approchées.
   Structure identique à celle visée pour l'import Wikidata / POP-Mérimée. */
window.CASTELLUM_FILTERS = {
  epoque: [
    { id: "e1", label: "Xe – XIIe s.", min: 10, max: 12 },
    { id: "e2", label: "XIIIe – XVe s.", min: 13, max: 15 },
    { id: "e3", label: "XVIe – XVIIe s.", min: 16, max: 17 },
    { id: "e4", label: "XVIIIe s. et +", min: 18, max: 21 }
  ],
  type: ["château", "château-fort", "forteresse", "manoir", "maison forte", "motte castrale", "palais", "domaine", "ruines", "enceinte fortifiée"],
  etat: ["Intact / restauré", "Bon état", "Partiellement ruiné", "Ruines", "Vestiges"],
  acces: ["Ouvert au public", "Visite partielle", "Privé, non visitable", "Extérieurs uniquement"]
};

/* Titres Wikipédia fr — servent à récupérer la photo de chaque fiche
   (vignette basse résolution mise en cache, version haute résolution en ligne). */
window.CASTELLUM_WIKI = {
  chambord: "Château de Chambord",
  chenonceau: "Château de Chenonceau",
  versailles: "Château de Versailles",
  carcassonne: "Cité de Carcassonne",
  gaillard: "Château-Gaillard (Les Andelys)",
  pierrefonds: "Château de Pierrefonds",
  vincennes: "Château de Vincennes",
  fougeres: "Château de Fougères",
  angers: "Château d'Angers",
  amboise: "Château d'Amboise",
  azay: "Château d'Azay-le-Rideau",
  usse: "Château d'Ussé",
  vitre: "Château de Vitré",
  beynac: "Château de Beynac",
  castelnaud: "Château de Castelnaud",
  bonaguil: "Château de Bonaguil",
  koenigsbourg: "Château du Haut-Kœnigsbourg",
  chantilly: "Château de Chantilly",
  fontainebleau: "Château de Fontainebleau",
  cheverny: "Château de Cheverny",
  villandry: "Château de Villandry",
  suscinio: "Château de Suscinio",
  peyrepertuse: "Château de Peyrepertuse",
  montsegur: "Château de Montségur",
  coucy: "Château de Coucy",
  loches: "Château de Loches",
  tarascon: "Château de Tarascon",
  salses: "Forteresse de Salses",
  murol: "Château de Murol",
  ango: "Manoir d'Ango",
  boves: "Château de Boves",
  tournoel: "Château de Tournoël",
  blois: "Château de Blois",
  foix: "Château de Foix",
  reignac: "Maison forte de Reignac"
};

window.CASTELLUM = [
  {
    id: "chambord", n: "Château de Chambord", v: ["Chambourg", "Domaine national de Chambord"],
    t: "château", sc: [16], per: "1519 – 1547", arch: "Attribué à Domenico da Cortona, chantier de François Ier",
    prop: ["François Ier", "Maison d'Orléans", "Maurice de Saxe", "État français (depuis 1930)"],
    ev: ["Chantier lancé par François Ier en 1519", "Séjours de Louis XIV et représentations de Molière", "Dépôt d'œuvres du Louvre en 1939-1945"],
    desc: "Plan centré à donjon cantonné de quatre tours, 440 pièces, escalier à double révolution et terrasses habitées peuplées de lanternes et cheminées.",
    st: ["Renaissance française"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Chambord", dep: "Loir-et-Cher (41)", reg: "Blésois / Orléanais", lat: 47.6160, lng: 1.5170,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.chambord.org" }]
  },
  {
    id: "chenonceau", n: "Château de Chenonceau", v: ["Château des Dames"],
    t: "château", sc: [16], per: "1513 – 1521, galerie 1576",
    arch: "Thomas Bohier, Philibert Delorme (galerie sur le Cher)",
    prop: ["Famille Bohier", "Diane de Poitiers", "Catherine de Médicis", "Famille Menier"],
    ev: ["Donné par Henri II à Diane de Poitiers", "Hôpital militaire en 1914-1918", "Ligne de démarcation en 1940-1942"],
    desc: "Corps de logis carré posé sur les piles d'un ancien moulin, prolongé par une galerie à deux étages franchissant le Cher.",
    st: ["Renaissance française", "Gothique tardif"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Chenonceaux", dep: "Indre-et-Loire (37)", reg: "Touraine", lat: 47.3247, lng: 1.0704,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.chenonceau.com" }]
  },
  {
    id: "versailles", n: "Château de Versailles", v: ["Palais de Versailles"],
    t: "palais", sc: [17, 18], per: "1623 – 1789",
    arch: "Louis Le Vau, Jules Hardouin-Mansart, André Le Nôtre (jardins)",
    prop: ["Louis XIII", "Louis XIV", "État français"],
    ev: ["Installation de la cour en 1682", "Signature du traité de Versailles en 1919", "Journées d'octobre 1789"],
    desc: "Enveloppe du pavillon de chasse de Louis XIII par une façade de marbre, galerie des Glaces de 73 m, aile du Midi et parc dessiné à la française.",
    st: ["Classicisme français", "Baroque"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Versailles", dep: "Yvelines (78)", reg: "Île-de-France", lat: 48.8049, lng: 2.1204,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.chateauversailles.fr" }]
  },
  {
    id: "carcassonne", n: "Cité de Carcassonne", v: ["Château comtal", "Carcaso"],
    t: "enceinte fortifiée", sc: [12, 13, 19], per: "XIIe s., remparts XIIIe s., restauration 1853-1879",
    arch: "Eugène Viollet-le-Duc (restauration)",
    prop: ["Vicomtes Trencavel", "Couronne de France", "État français"],
    ev: ["Siège de 1209 pendant la croisade albigeoise", "Déclassement militaire en 1804", "Restauration par Viollet-le-Duc"],
    desc: "Double enceinte de 3 km, 52 tours, château comtal adossé au rempart occidental et lices entre les deux murs.",
    st: ["Roman", "Gothique", "Restauration du XIXe s."], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Carcassonne", dep: "Aude (11)", reg: "Languedoc", lat: 43.2061, lng: 2.3639,
    plan: true, liens: [{ label: "Centre des monuments nationaux", url: "https://www.remparts-carcassonne.fr" }]
  },
  {
    id: "gaillard", n: "Château-Gaillard", v: ["Castrum de Roche d'Andely"],
    t: "ruines", sc: [12], per: "1196 – 1198", arch: "Commandé par Richard Cœur de Lion",
    prop: ["Duché de Normandie", "Couronne de France", "Commune des Andelys"],
    ev: ["Siège de Philippe Auguste en 1203-1204", "Démantèlement ordonné en 1599"],
    desc: "Éperon barré au-dessus de la Seine : donjon cylindrique à becs, chemise ondulée et triple enceinte étagée.",
    st: ["Architecture militaire anglo-normande"], etat: "Ruines",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Visite partielle",
    com: "Les Andelys", dep: "Eure (27)", reg: "Normandie", lat: 49.2381, lng: 1.4083,
    plan: true, liens: []
  },
  {
    id: "pierrefonds", n: "Château de Pierrefonds", v: ["Pierrefonds-le-Château"],
    t: "château-fort", sc: [14, 19], per: "1393 – 1407, reconstruction 1857-1885",
    arch: "Jean Le Noir, puis Eugène Viollet-le-Duc",
    prop: ["Louis d'Orléans", "Napoléon Ier", "État français"],
    ev: ["Démantèlement sous Richelieu en 1617", "Reconstruction pour Napoléon III"],
    desc: "Quadrilatère à huit tours d'angle, chemin de ronde couvert et salle des Preuses ; relecture savante du château fort par le XIXe siècle.",
    st: ["Gothique flamboyant", "Restauration du XIXe s."], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Pierrefonds", dep: "Oise (60)", reg: "Valois / Picardie", lat: 49.3479, lng: 2.9781,
    plan: true, liens: [{ label: "Centre des monuments nationaux", url: "https://www.chateau-pierrefonds.fr" }]
  },
  {
    id: "vincennes", n: "Château de Vincennes", v: ["Donjon de Vincennes"],
    t: "forteresse", sc: [14], per: "1337 – 1410", arch: "Chantier de Philippe VI à Charles V",
    prop: ["Couronne de France", "Armée française", "État français"],
    ev: ["Mort d'Henri V d'Angleterre en 1422", "Prison d'État aux XVIIe-XVIIIe s.", "Exécution de Mata Hari en 1917"],
    desc: "Donjon de 52 m dans sa chemise, enceinte rectangulaire de neuf tours et Sainte-Chapelle royale au flanc est.",
    st: ["Gothique rayonnant"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Vincennes", dep: "Val-de-Marne (94)", reg: "Île-de-France", lat: 48.8425, lng: 2.4358,
    plan: true, liens: [{ label: "Centre des monuments nationaux", url: "https://www.chateau-vincennes.fr" }]
  },
  {
    id: "fougeres", n: "Château de Fougères", v: ["Fulgerium"],
    t: "château-fort", sc: [12, 13, 15], per: "XIIe – XVe s.", arch: "Famille de Fougères, ducs de Bretagne",
    prop: ["Seigneurs de Fougères", "Duché de Bretagne", "Commune de Fougères"],
    ev: ["Prise par Henri II Plantagenêt en 1166", "Coup de main breton de 1449, déclencheur de la reprise de la guerre de Cent Ans"],
    desc: "Deux hectares dans un méandre du Nançon : treize tours, enceinte basse en éperon et tours à canon de la fin du Moyen Âge.",
    st: ["Militaire médiéval breton"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Fougères", dep: "Ille-et-Vilaine (35)", reg: "Bretagne", lat: 48.3527, lng: -1.2075,
    plan: true, liens: []
  },
  {
    id: "angers", n: "Château d'Angers", v: ["Château des ducs d'Anjou"],
    t: "forteresse", sc: [13], per: "1230 – 1240", arch: "Chantier de Blanche de Castille",
    prop: ["Comtes d'Anjou", "Maison Valois-Anjou", "État français"],
    ev: ["Commande de la tenture de l'Apocalypse en 1375", "Rasement partiel ordonné en 1585"],
    desc: "Enceinte de schiste et calcaire à dix-sept tours en damier, sur un promontoire dominant la Maine ; abrite la tenture de l'Apocalypse.",
    st: ["Gothique", "Militaire capétien"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Angers", dep: "Maine-et-Loire (49)", reg: "Anjou", lat: 47.4700, lng: -0.5600,
    plan: true, liens: [{ label: "Centre des monuments nationaux", url: "https://www.chateau-angers.fr" }]
  },
  {
    id: "amboise", n: "Château royal d'Amboise", v: ["Ambacia"],
    t: "château", sc: [15, 16], per: "1492 – 1498", arch: "Chantiers de Charles VIII et Louis XII",
    prop: ["Famille d'Amboise", "Couronne de France", "Fondation Saint-Louis"],
    ev: ["Conjuration d'Amboise en 1560", "Sépulture de Léonard de Vinci dans la chapelle Saint-Hubert"],
    desc: "Terrasse dominant la Loire, logis du Roi à lucarnes gothiques, tours cavalières à rampe et chapelle Saint-Hubert.",
    st: ["Gothique flamboyant", "Première Renaissance"], etat: "Bon état",
    stat: ["Monument historique classé", "Château privé", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Amboise", dep: "Indre-et-Loire (37)", reg: "Touraine", lat: 47.4133, lng: 0.9861,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.chateau-amboise.com" }]
  },
  {
    id: "azay", n: "Château d'Azay-le-Rideau", v: ["Azay-le-Brûlé"],
    t: "château", sc: [16], per: "1518 – 1527", arch: "Gilles Berthelot, maîtrise d'ouvrage de Philippe Lesbahy",
    prop: ["Gilles Berthelot", "Marquis de Biencourt", "État français"],
    ev: ["Incendie du bourg par Charles VII en 1418", "Acquisition par l'État en 1905"],
    desc: "Plan en L posé sur l'Indre, escalier droit à loggias superposées et miroir d'eau sur trois côtés.",
    st: ["Renaissance française"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Azay-le-Rideau", dep: "Indre-et-Loire (37)", reg: "Touraine", lat: 47.2589, lng: 0.4661,
    plan: true, liens: []
  },
  {
    id: "usse", n: "Château d'Ussé", v: ["Château de la Belle au bois dormant"],
    t: "château", sc: [15, 16, 17], per: "XVe – XVIIe s.", arch: "Familles de Bueil et d'Espinay",
    prop: ["Famille de Bueil", "Famille d'Espinay", "Famille de Blacas"],
    ev: ["Séjour de Vauban, gendre du propriétaire", "Inspiration prêtée au conte de Perrault"],
    desc: "Terrasses étagées au-dessus de l'Indre, courtines à mâchicoulis décoratifs et forêt de toitures d'ardoise.",
    st: ["Gothique tardif", "Renaissance", "Classique"], etat: "Bon état",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Rigny-Ussé", dep: "Indre-et-Loire (37)", reg: "Touraine", lat: 47.2494, lng: 0.2919,
    plan: false, liens: []
  },
  {
    id: "vitre", n: "Château de Vitré", v: ["Vitreium"],
    t: "château-fort", sc: [13, 15], per: "XIIIe – XVe s.", arch: "Barons de Vitré, famille de Laval",
    prop: ["Barons de Vitré", "Famille de La Trémoille", "Commune de Vitré"],
    ev: ["Résistance aux sièges anglais de la guerre de Cent Ans", "Réunion des États de Bretagne en 1655"],
    desc: "Plan triangulaire sur éperon, châtelet à deux tours et pont-levis, tour Saint-Laurent et courtines à archères.",
    st: ["Gothique militaire breton"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Vitré", dep: "Ille-et-Vilaine (35)", reg: "Bretagne", lat: 48.1236, lng: -1.2153,
    plan: false, liens: []
  },
  {
    id: "beynac", n: "Château de Beynac", v: ["Beynac-et-Cazenac"],
    t: "château-fort", sc: [12, 13, 14], per: "XIIe – XIVe s.", arch: "Baronnie de Beynac",
    prop: ["Barons de Beynac", "Famille de Beaumont", "Propriétaire privé"],
    ev: ["Occupation par Richard Cœur de Lion vers 1195", "Face à Castelnaud pendant la guerre de Cent Ans"],
    desc: "Falaise de 150 m au-dessus de la Dordogne : donjon roman, double enceinte et salle des États voûtée en berceau brisé.",
    st: ["Roman", "Gothique"], etat: "Bon état",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Beynac-et-Cazenac", dep: "Dordogne (24)", reg: "Périgord", lat: 44.8394, lng: 1.1447,
    plan: false, liens: []
  },
  {
    id: "castelnaud", n: "Château de Castelnaud-la-Chapelle", v: ["Castelnaud-Fayrac"],
    t: "château-fort", sc: [13, 15], per: "XIIIe – XVe s.", arch: "Familles de Castelnaud et de Caumont",
    prop: ["Bernard de Casnac", "Famille de Caumont", "Propriétaire privé"],
    ev: ["Pris par Simon de Montfort en 1214", "Occupations alternées anglaises et françaises au XIVe s."],
    desc: "Donjon barlong, barbacane et tour d'artillerie ; musée de la guerre au Moyen Âge et machines de siège sur la terrasse.",
    st: ["Militaire médiéval"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Castelnaud-la-Chapelle", dep: "Dordogne (24)", reg: "Périgord", lat: 44.8175, lng: 1.1533,
    plan: true, liens: []
  },
  {
    id: "bonaguil", n: "Château de Bonaguil", v: ["Bona Acucula"],
    t: "forteresse", sc: [13, 15, 16], per: "XIIIe s., transformation 1480-1520",
    arch: "Bérenger de Roquefeuil",
    prop: ["Famille de Roquefeuil", "Commune de Fumel"],
    ev: ["Chantier d'adaptation à l'artillerie sur quarante ans", "Vendu comme bien national en 1789"],
    desc: "Dernière grande forteresse médiévale française : donjon en proue, casemates, canonnières et enceinte adaptée à la poudre.",
    st: ["Gothique militaire", "Architecture de transition"], etat: "Partiellement ruiné",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Saint-Front-sur-Lémance", dep: "Lot-et-Garonne (47)", reg: "Quercy / Agenais", lat: 44.5433, lng: 0.9903,
    plan: true, liens: []
  },
  {
    id: "koenigsbourg", n: "Château du Haut-Kœnigsbourg", v: ["Burg Hohkönigsburg", "Staufenberg"],
    t: "château-fort", sc: [12, 15, 20], per: "1147, reconstruction 1900-1908",
    arch: "Bodo Ebhardt (reconstruction)",
    prop: ["Hohenstaufen", "Famille de Thierstein", "État français"],
    ev: ["Incendie par les Suédois en 1633", "Reconstruction offerte à Guillaume II en 1899"],
    desc: "Éperon de grès rose à 757 m : grand bastion, donjon carré et logis seigneurial restitués dans l'esprit du XVe siècle.",
    st: ["Gothique", "Reconstitution historiciste"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété départementale"], acc: "Ouvert au public",
    com: "Orschwiller", dep: "Bas-Rhin (67)", reg: "Alsace", lat: 48.2494, lng: 7.3444,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.chateau-hautkoenigsbourg.fr" }]
  },
  {
    id: "chantilly", n: "Château de Chantilly", v: ["Domaine de Chantilly"],
    t: "domaine", sc: [16, 19], per: "Petit Château 1560, Grand Château 1875-1882",
    arch: "Jean Bullant, Honoré Daumet (reconstruction)",
    prop: ["Famille de Montmorency", "Princes de Condé", "Institut de France"],
    ev: ["Démolition révolutionnaire du Grand Château", "Legs à l'Institut de France par le duc d'Aumale en 1886"],
    desc: "Château sur pièce d'eau, Grandes Écuries de Jean Aubert et parc de Le Nôtre ; abrite le musée Condé.",
    st: ["Renaissance", "Néo-Renaissance"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Chantilly", dep: "Oise (60)", reg: "Picardie / Valois", lat: 49.1936, lng: 2.4853,
    plan: true, liens: [{ label: "Site officiel", url: "https://chateaudechantilly.fr" }]
  },
  {
    id: "fontainebleau", n: "Château de Fontainebleau", v: ["Palais de Fontainebleau"],
    t: "palais", sc: [16, 17, 18], per: "XIIe s., refonte à partir de 1528",
    arch: "Gilles Le Breton, Primatice, Philibert Delorme",
    prop: ["Capétiens", "François Ier", "Napoléon Ier", "État français"],
    ev: ["Édit de Fontainebleau en 1685", "Abdication de Napoléon en 1814"],
    desc: "Suite de cours et de galeries de huit siècles : galerie François Ier, escalier en fer à cheval, appartements impériaux.",
    st: ["Renaissance", "Classique", "Empire"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété de l'État", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Fontainebleau", dep: "Seine-et-Marne (77)", reg: "Île-de-France / Gâtinais", lat: 48.4022, lng: 2.6997,
    plan: true, liens: [{ label: "Site officiel", url: "https://www.chateaudefontainebleau.fr" }]
  },
  {
    id: "cheverny", n: "Château de Cheverny", v: ["Cheverny"],
    t: "château", sc: [17], per: "1624 – 1630", arch: "Jacques Bougier",
    prop: ["Famille Hurault", "Marquis de Vibraye"],
    ev: ["Dépôt d'œuvres du Louvre en 1939", "Ouverture au public dès 1922"],
    desc: "Façade de pierre de Bourré d'une seule campagne, symétrie stricte, intérieurs Louis XIII conservés.",
    st: ["Classicisme Louis XIII"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé"], acc: "Ouvert au public",
    com: "Cheverny", dep: "Loir-et-Cher (41)", reg: "Sologne / Blésois", lat: 47.5003, lng: 1.4581,
    plan: false, liens: []
  },
  {
    id: "villandry", n: "Château de Villandry", v: ["Colombiers"],
    t: "château", sc: [16], per: "1532 – 1536", arch: "Jean Le Breton",
    prop: ["Jean Le Breton", "Marquis de Castellane", "Famille Carvallo"],
    ev: ["Signature de la paix des Colombiers en 1189", "Restitution des jardins Renaissance à partir de 1906"],
    desc: "Trois corps de logis en U autour d'une cour ouverte sur la vallée, donjon médiéval conservé, jardins en terrasses ordonnés.",
    st: ["Renaissance française"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Château privé", "Patrimoine mondial UNESCO"], acc: "Ouvert au public",
    com: "Villandry", dep: "Indre-et-Loire (37)", reg: "Touraine", lat: 47.3403, lng: 0.5136,
    plan: true, liens: []
  },
  {
    id: "suscinio", n: "Château de Suscinio", v: ["Susinioc", "Château des ducs de Bretagne"],
    t: "château-fort", sc: [13, 15], per: "XIIIe – XVe s.", arch: "Ducs de Bretagne",
    prop: ["Ducs de Bretagne", "Département du Morbihan"],
    ev: ["Résidence de chasse ducale", "Carrière de pierre au XIXe s. avant sauvetage en 1965"],
    desc: "Plate-forme entourée de douves en eau face aux marais, six tours, pavements de terre cuite du XIVe siècle.",
    st: ["Gothique militaire breton"], etat: "Partiellement ruiné",
    stat: ["Monument historique classé", "Propriété départementale"], acc: "Ouvert au public",
    com: "Sarzeau", dep: "Morbihan (56)", reg: "Bretagne", lat: 47.5150, lng: -2.7000,
    plan: true, liens: []
  },
  {
    id: "peyrepertuse", n: "Château de Peyrepertuse", v: ["Petra Pertusa", "Citadelle du vertige"],
    t: "ruines", sc: [11, 13], per: "XIe s., extension royale 1250-1251",
    arch: "Chantier de Saint Louis (donjon Saint-Jordi)",
    prop: ["Comtes de Barcelone", "Couronne de France", "Commune de Duilhac"],
    ev: ["Reddition au roi de France en 1240", "Abandon après le traité des Pyrénées de 1659"],
    desc: "Crête calcaire de 300 m de long à 800 m d'altitude, deux châteaux reliés par l'escalier Saint-Louis taillé dans le roc.",
    st: ["Roman", "Militaire royal"], etat: "Ruines",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Duilhac-sous-Peyrepertuse", dep: "Aude (11)", reg: "Languedoc / Corbières", lat: 42.8697, lng: 2.5561,
    plan: true, liens: []
  },
  {
    id: "montsegur", n: "Château de Montségur", v: ["Montsegur", "Pog de Montségur"],
    t: "ruines", sc: [13], per: "Reconstruction après 1244", arch: "Guilhem de Peyrepertuse (place cathare)",
    prop: ["Comtes de Foix", "Couronne de France", "Commune de Montségur"],
    ev: ["Siège de dix mois et bûcher de 1244", "Fouilles archéologiques depuis 1964"],
    desc: "Enceinte polygonale sur un pog à 1207 m, donjon à citerne ; les vestiges visibles sont postérieurs au siège.",
    st: ["Militaire médiéval languedocien"], etat: "Ruines",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Montségur", dep: "Ariège (09)", reg: "Comté de Foix", lat: 42.8756, lng: 1.8322,
    plan: true, liens: []
  },
  {
    id: "coucy", n: "Château de Coucy", v: ["Coucy-le-Château-Auffrique"],
    t: "ruines", sc: [13], per: "1225 – 1242", arch: "Enguerrand III de Coucy",
    prop: ["Sires de Coucy", "Maison d'Orléans", "État français"],
    ev: ["Démantèlement partiel en 1652", "Donjon dynamité par l'armée allemande en 1917"],
    desc: "Le plus grand donjon d'Occident (54 m, 31 m de diamètre) réduit à sa base ; enceinte urbaine et basse-cour subsistantes.",
    st: ["Gothique militaire"], etat: "Ruines",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Coucy-le-Château-Auffrique", dep: "Aisne (02)", reg: "Picardie / Laonnois", lat: 49.5203, lng: 3.3236,
    plan: true, liens: []
  },
  {
    id: "loches", n: "Cité royale de Loches", v: ["Donjon de Loches", "Logis royal"],
    t: "forteresse", sc: [11, 15], per: "Donjon vers 1013, logis XVe s.",
    arch: "Foulques Nerra (donjon)",
    prop: ["Comtes d'Anjou", "Couronne de France", "Département d'Indre-et-Loire"],
    ev: ["Captivité de Ludovic Sforza", "Séjours de Jeanne d'Arc et d'Agnès Sorel"],
    desc: "Donjon rectangulaire de 36 m parmi les plus anciens conservés, logis royal gothique et flamboyant, enceinte urbaine complète.",
    st: ["Roman", "Gothique flamboyant"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété départementale"], acc: "Ouvert au public",
    com: "Loches", dep: "Indre-et-Loire (37)", reg: "Touraine", lat: 47.1272, lng: 0.9994,
    plan: true, liens: []
  },
  {
    id: "tarascon", n: "Château de Tarascon", v: ["Château du roi René"],
    t: "château-fort", sc: [15], per: "1400 – 1449", arch: "Chantier de Louis II et du roi René d'Anjou",
    prop: ["Maison d'Anjou", "État français", "Commune de Tarascon"],
    ev: ["Prison d'État de 1720 à 1926", "Graffitis de marins anglais dans les salles hautes"],
    desc: "Bloc quadrangulaire de pierre de taille les pieds dans le Rhône, terrasse sommitale unique et cour à galerie.",
    st: ["Gothique provençal"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Tarascon", dep: "Bouches-du-Rhône (13)", reg: "Provence", lat: 43.8060, lng: 4.6597,
    plan: true, liens: []
  },
  {
    id: "salses", n: "Forteresse de Salses", v: ["Fortaleza de Salses"],
    t: "forteresse", sc: [15], per: "1497 – 1503", arch: "Francisco Ramiro López",
    prop: ["Couronne d'Aragon", "Couronne de France", "État français"],
    ev: ["Siège franco-espagnol de 1639-1640", "Rattachement à la France en 1659"],
    desc: "Fortification semi-enterrée à murs de 10 m d'épaisseur : cas d'école du passage du château fort au bastion d'artillerie.",
    st: ["Militaire hispano-mauresque", "Transition artillerie"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété de l'État"], acc: "Ouvert au public",
    com: "Salses-le-Château", dep: "Pyrénées-Orientales (66)", reg: "Roussillon", lat: 42.8386, lng: 2.9169,
    plan: true, liens: []
  },
  {
    id: "murol", n: "Château de Murol", v: ["Murol-en-Auvergne"],
    t: "château-fort", sc: [12, 15], per: "XIIe – XVe s.", arch: "Famille de Murol, Guillaume de Sam",
    prop: ["Famille de Murol", "Famille d'Estaing", "Commune de Murol"],
    ev: ["Épargné à la Révolution par la protection de Lafayette", "Reconstitutions médiévales depuis 1985"],
    desc: "Basalte sur piton volcanique : enceinte polygonale, chapelle et logis Renaissance greffé au flanc sud.",
    st: ["Roman", "Gothique", "Renaissance"], etat: "Partiellement ruiné",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Murol", dep: "Puy-de-Dôme (63)", reg: "Auvergne", lat: 45.5772, lng: 2.9394,
    plan: false, liens: []
  },
  {
    id: "ango", n: "Manoir d'Ango", v: ["Manoir de Jehan Ango"],
    t: "manoir", sc: [16], per: "1530 – 1545", arch: "Commande de l'armateur Jean Ango",
    prop: ["Jean Ango", "Propriétaires privés successifs"],
    ev: ["Résidence d'été de l'armateur de François Ier", "Séjours d'artistes au XXe s."],
    desc: "Cour fermée de bâtiments à damiers de silex et brique, colombier monumental à coupole, loggia d'inspiration italienne.",
    st: ["Renaissance normande"], etat: "Bon état",
    stat: ["Monument historique classé", "Château privé"], acc: "Visite partielle",
    com: "Varengeville-sur-Mer", dep: "Seine-Maritime (76)", reg: "Normandie / Pays de Caux", lat: 49.9078, lng: 0.9989,
    plan: false, liens: []
  },
  {
    id: "boves", n: "Motte castrale de Boves", v: ["Castrum de Bova"],
    t: "motte castrale", sc: [10, 11, 13], per: "Xe – XIIIe s.", arch: "Seigneurs de Boves",
    prop: ["Seigneurs de Boves", "Commune de Boves"],
    ev: ["Fouilles programmées depuis 1996", "Abandon progressif après le XVe s."],
    desc: "Motte de terre de 20 m surmontée des vestiges d'une tour de pierre ; référence pour l'archéologie des mottes du nord de la France.",
    st: ["Fortification de terre"], etat: "Vestiges",
    stat: ["Monument historique inscrit", "Propriété communale"], acc: "Extérieurs uniquement",
    com: "Boves", dep: "Somme (80)", reg: "Picardie / Amiénois", lat: 49.8397, lng: 2.4033,
    plan: true, liens: []
  },
  {
    id: "tournoel", n: "Château de Tournoël", v: ["Tornoellum"],
    t: "ruines", sc: [12, 13], per: "XIIe – XIIIe s.", arch: "Comtes d'Auvergne",
    prop: ["Comtes d'Auvergne", "Famille de La Fayette", "Propriétaire privé"],
    ev: ["Prise par Guy de Dampierre pour Philippe Auguste en 1213", "Ruiné après un incendie au XVIIe s."],
    desc: "Donjon rond et donjon carré jumelés au-dessus de la Limagne, cuisine voûtée et courtines de basalte.",
    st: ["Roman", "Gothique"], etat: "Partiellement ruiné",
    stat: ["Monument historique classé", "Château privé"], acc: "Visite partielle",
    com: "Volvic", dep: "Puy-de-Dôme (63)", reg: "Auvergne / Limagne", lat: 45.8639, lng: 3.0464,
    plan: false, liens: []
  },
  {
    id: "blois", n: "Château royal de Blois", v: ["Blois", "Blesum castrum"],
    t: "château", sc: [13, 15, 16, 17], per: "XIIIe – XVIIe s.",
    arch: "Louis XII, François Ier, François Mansart (aile Gaston d'Orléans)",
    prop: ["Comtes de Blois", "Maison d'Orléans", "Commune de Blois"],
    ev: ["États généraux de 1576 et 1588", "Assassinat du duc de Guise en 1588"],
    desc: "Quatre ailes, quatre siècles autour d'une cour : gothique, brique et pierre Louis XII, escalier François Ier, façade classique.",
    st: ["Gothique", "Renaissance", "Classique"], etat: "Intact / restauré",
    stat: ["Monument historique classé", "Propriété communale"], acc: "Ouvert au public",
    com: "Blois", dep: "Loir-et-Cher (41)", reg: "Blésois", lat: 47.5861, lng: 1.3306,
    plan: true, liens: []
  },
  {
    id: "reignac", n: "Maison forte de Reignac", v: ["Château de Reignac", "Reignac troglodytique"],
    t: "maison forte", sc: [14, 15, 16], per: "XIVe – XVIe s.", arch: "Seigneurs de Reignac, adaptation d'un abri sous roche",
    prop: ["Famille de Reignac", "Famille de Beynac", "Propriétaire privé"],
    ev: ["Occupation du site depuis la préhistoire", "Habitat seigneurial continu jusqu'au XIXe s.", "Ouverture à la visite en 2006"],
    desc: "Logis encastré dans la falaise de la Vézère : façade de pierre plaquée contre l'abri sous roche, salles troglodytiques, cuisine et chemin de ronde creusés dans le rocher.",
    st: ["Vernaculaire fortifié", "Troglodytique"], etat: "Intact / restauré",
    stat: ["Monument historique inscrit", "Château privé"], acc: "Ouvert au public",
    com: "Tursac", dep: "Dordogne (24)", reg: "Périgord noir", lat: 44.9628, lng: 1.0472,
    plan: false, liens: []
  },
  {
    id: "foix", n: "Château de Foix", v: ["Castèl de Fois"],
    t: "château-fort", sc: [11, 14, 15], per: "XIe – XVe s.", arch: "Comtes de Foix",
    prop: ["Comtes de Foix", "Couronne de France", "Département de l'Ariège"],
    ev: ["Siège de Simon de Montfort en 1211-1212", "Prison de 1862 à 1930"],
    desc: "Trois tours d'époques différentes sur un rocher dominant l'Ariège, reliées par des courtines étroites.",
    st: ["Roman", "Gothique"], etat: "Bon état",
    stat: ["Monument historique classé", "Propriété départementale"], acc: "Ouvert au public",
    com: "Foix", dep: "Ariège (09)", reg: "Comté de Foix", lat: 42.9661, lng: 1.6053,
    plan: true, liens: []
  }
];
